// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS App2Container (A2C)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsapp2container.html
 *
 * 2025-02-24T21:46:40.679Z
 */
export enum AwsA2cActions {
  /**
   * Grants permission to get the details of all Containerization jobs
   *
   * See https://docs.aws.amazon.com/tk-dotnet-refactoring/latest/userguide/what-is-tk-dotnet-refactoring.html
   */
  GetContainerizationJobDetails = 'a2c:GetContainerizationJobDetails',
  /**
   * Grants permission to get the details of all Deployment jobs
   *
   * See https://docs.aws.amazon.com/tk-dotnet-refactoring/latest/userguide/what-is-tk-dotnet-refactoring.html
   */
  GetDeploymentJobDetails = 'a2c:GetDeploymentJobDetails',
  /**
   * Grants permission to start a Containerization job
   *
   * See https://docs.aws.amazon.com/tk-dotnet-refactoring/latest/userguide/what-is-tk-dotnet-refactoring.html
   */
  StartContainerizationJob = 'a2c:StartContainerizationJob',
  /**
   * Grants permission to start a Deploymnet job
   *
   * See https://docs.aws.amazon.com/tk-dotnet-refactoring/latest/userguide/what-is-tk-dotnet-refactoring.html
   */
  StartDeploymentJob = 'a2c:StartDeploymentJob',
}
