// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Backup storage (BACKUP-STORAGE)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsbackupstorage.html
 *
 * 2024-02-12T09:56:11.017Z
 */
export enum AwsBackupStorageActions {
  /**
   * Grants permission to commit backup job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  CommitBackupJob = 'backup-storage:CommitBackupJob',
  /**
   * Grants permission to delete objects
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  DeleteObjects = 'backup-storage:DeleteObjects',
  /**
   * Grants permission to describe backup job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  DescribeBackupJob = 'backup-storage:DescribeBackupJob',
  /**
   * Grants permission to get base backup
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  GetBaseBackup = 'backup-storage:GetBaseBackup',
  /**
   * Grants permission to get data from a recovery point for a restore job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  GetChunk = 'backup-storage:GetChunk',
  /**
   * Grants permission to get incremental base backup
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  GetIncrementalBaseBackup = 'backup-storage:GetIncrementalBaseBackup',
  /**
   * Grants permission to get metadata from a recovery point for a restore job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  GetObjectMetadata = 'backup-storage:GetObjectMetadata',
  /**
   * Grants permission to list data from a recovery point for a restore job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  ListChunks = 'backup-storage:ListChunks',
  /**
   * Grants permission to list data from a recovery point for a restore job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  ListObjects = 'backup-storage:ListObjects',
  /**
   * Associates a KMS key to a backup vault
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/API_CreateBackupVault.html
   */
  MountCapsule = 'backup-storage:MountCapsule',
  /**
   * Grants permission to mark an uploaded data as completed for a backup job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  NotifyObjectComplete = 'backup-storage:NotifyObjectComplete',
  /**
   * Grants permission to upload data to an AWS Backup-managed recovery point for a
   * backup job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  PutChunk = 'backup-storage:PutChunk',
  /**
   * Grants permission to put object
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  PutObject = 'backup-storage:PutObject',
  /**
   * Grants permission to upload data to an AWS Backup-managed recovery point for a
   * backup job
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  StartObject = 'backup-storage:StartObject',
  /**
   * Grants permission to update object complete
   *
   * See https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-data-transfer.html
   */
  UpdateObjectComplete = 'backup-storage:UpdateObjectComplete',
}
