// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon CloudWatch (CLOUDWATCH)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatch.html
 *
 * 2025-02-24T21:47:06.580Z
 */
export enum AwsCloudwatchActions {
  /**
   * Grants permission to batch get service level indicator report
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  BatchGetServiceLevelIndicatorReport = 'cloudwatch:BatchGetServiceLevelIndicatorReport',
  /**
   * Grants permission to batch retrieve a service level objective budget report
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  BatchGetServiceLevelObjectiveBudgetReport = 'cloudwatch:BatchGetServiceLevelObjectiveBudgetReport',
  /**
   * Grants permission to create a service level objective
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  CreateServiceLevelObjective = 'cloudwatch:CreateServiceLevelObjective',
  /**
   * Grants permission to delete a collection of alarms
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteAlarms.html
   */
  DeleteAlarms = 'cloudwatch:DeleteAlarms',
  /**
   * Grants permission to delete the specified anomaly detection model from your acc
   * ount
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteAnomalyDetector.html
   */
  DeleteAnomalyDetector = 'cloudwatch:DeleteAnomalyDetector',
  /**
   * Grants permission to delete all CloudWatch dashboards that you specify
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteDashboards.html
   */
  DeleteDashboards = 'cloudwatch:DeleteDashboards',
  /**
   * Grants permission to delete a collection of insight rules
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteInsightRules.html
   */
  DeleteInsightRules = 'cloudwatch:DeleteInsightRules',
  /**
   * Grants permission to delete the CloudWatch metric stream that you specify
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteMetricStream.html
   */
  DeleteMetricStream = 'cloudwatch:DeleteMetricStream',
  /**
   * Grants permission to delete a service level objective
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  DeleteServiceLevelObjective = 'cloudwatch:DeleteServiceLevelObjective',
  /**
   * Grants permission to retrieve the history for the specified alarm
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarmHistory.html
   */
  DescribeAlarmHistory = 'cloudwatch:DescribeAlarmHistory',
  /**
   * Grants permission to describe all alarms, currently owned by the user's account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarms.html
   */
  DescribeAlarms = 'cloudwatch:DescribeAlarms',
  /**
   * Grants permission to describe all alarms configured on the specified metric, cu
   * rrently owned by the user's account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarmsForMetric.html
   */
  DescribeAlarmsForMetric = 'cloudwatch:DescribeAlarmsForMetric',
  /**
   * Grants permission to list the anomaly detection models that you have created in
   * your account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAnomalyDetectors.html
   */
  DescribeAnomalyDetectors = 'cloudwatch:DescribeAnomalyDetectors',
  /**
   * Grants permission to describe all insight rules, currently owned by the user's
   * account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeInsightRules.html
   */
  DescribeInsightRules = 'cloudwatch:DescribeInsightRules',
  /**
   * Grants permission to disable actions for a collection of alarms
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DisableAlarmActions.html
   */
  DisableAlarmActions = 'cloudwatch:DisableAlarmActions',
  /**
   * Grants permission to disable a collection of insight rules
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DisableInsightRules.html
   */
  DisableInsightRules = 'cloudwatch:DisableInsightRules',
  /**
   * Grants permission to enable actions for a collection of alarms
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_EnableAlarmActions.html
   */
  EnableAlarmActions = 'cloudwatch:EnableAlarmActions',
  /**
   * Grants permission to enable a collection of insight rules
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_EnableInsightRules.html
   */
  EnableInsightRules = 'cloudwatch:EnableInsightRules',
  /**
   * Grants permission to enable a CloudWatch topology discovery
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  EnableTopologyDiscovery = 'cloudwatch:EnableTopologyDiscovery',
  /**
   * Grants permission to generate a Metrics Insights or Logs Insights query string
   * from a natural language prompt
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-query-assist.html
   */
  GenerateQuery = 'cloudwatch:GenerateQuery',
  /**
   * Grants permission to display the details of the CloudWatch dashboard you specif
   * y
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetDashboard.html
   */
  GetDashboard = 'cloudwatch:GetDashboard',
  /**
   * Grants permission to return the top-N report of unique contributors over a time
   * range for a given insight rule
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetInsightRuleReport.html
   */
  GetInsightRuleReport = 'cloudwatch:GetInsightRuleReport',
  /**
   * Grants permission to retrieve batch amounts of CloudWatch metric data and perfo
   * rm metric math on retrieved data
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html
   */
  GetMetricData = 'cloudwatch:GetMetricData',
  /**
   * Grants permission to retrieve statistics for the specified metric
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html
   */
  GetMetricStatistics = 'cloudwatch:GetMetricStatistics',
  /**
   * Grants permission to return the details of a CloudWatch metric stream
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStream.html
   */
  GetMetricStream = 'cloudwatch:GetMetricStream',
  /**
   * Grants permission to retrieve snapshots of metric widgets
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricWidgetImage.html
   */
  GetMetricWidgetImage = 'cloudwatch:GetMetricWidgetImage',
  /**
   * Grants permission to retrieve information about a service
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  GetService = 'cloudwatch:GetService',
  /**
   * Grants permission to retrieve service data
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/permissions-reference-cw.html
   */
  GetServiceData = 'cloudwatch:GetServiceData',
  /**
   * Grants permission to retrieve information about service level objective
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  GetServiceLevelObjective = 'cloudwatch:GetServiceLevelObjective',
  /**
   * Grants permission to retrieve a CloudWatch topology discovery status
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/permissions-reference-cw.html
   */
  GetTopologyDiscoveryStatus = 'cloudwatch:GetTopologyDiscoveryStatus',
  /**
   * Grants permission to retrieve a CloudWatch topology map
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  GetTopologyMap = 'cloudwatch:GetTopologyMap',
  /**
   * Grants permission to share CloudWatch resources with a monitoring account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account-Setup.html#CloudWatch-Unified-Cross-Account-Setup-permissions
   */
  Link = 'cloudwatch:Link',
  /**
   * Grants permission to return a list of all CloudWatch dashboards in your account
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListDashboards.html
   */
  ListDashboards = 'cloudwatch:ListDashboards',
  /**
   * Grants permission to retrieve all the entities that are emitting a given metric
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/permissions-reference-cw.html
   */
  ListEntitiesForMetric = 'cloudwatch:ListEntitiesForMetric',
  /**
   * Grants permission to list available managed Insight Rules for a given Resource
   * ARN
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListManagedInsightRules.html
   */
  ListManagedInsightRules = 'cloudwatch:ListManagedInsightRules',
  /**
   * Grants permission to return a list of all CloudWatch metric streams in your acc
   * ount
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetricStreams.html
   */
  ListMetricStreams = 'cloudwatch:ListMetricStreams',
  /**
   * Grants permission to retrieve a list of valid metrics stored for the AWS accoun
   * t owner
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html
   */
  ListMetrics = 'cloudwatch:ListMetrics',
  /**
   * Grants permission to list service level objectives
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  ListServiceLevelObjectives = 'cloudwatch:ListServiceLevelObjectives',
  /**
   * Grants permission to list services
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  ListServices = 'cloudwatch:ListServices',
  /**
   * Grants permission to list tags for an Amazon CloudWatch resource
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'cloudwatch:ListTagsForResource',
  /**
   * Grants permission to create or update an anomaly detection model for a CloudWat
   * ch metric
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutAnomalyDetector.html
   */
  PutAnomalyDetector = 'cloudwatch:PutAnomalyDetector',
  /**
   * Grants permission to create or update a composite alarm
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutCompositeAlarm.html
   */
  PutCompositeAlarm = 'cloudwatch:PutCompositeAlarm',
  /**
   * Grants permission to create a CloudWatch dashboard, or update an existing dashb
   * oard if it already exists
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutDashboard.html
   */
  PutDashboard = 'cloudwatch:PutDashboard',
  /**
   * Grants permission to create a new insight rule or replace an existing insight r
   * ule
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutInsightRule.html
   */
  PutInsightRule = 'cloudwatch:PutInsightRule',
  /**
   * Grants permission to create managed Insight Rules
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutManagedInsightRules.html
   */
  PutManagedInsightRules = 'cloudwatch:PutManagedInsightRules',
  /**
   * Grants permission to create or update an alarm and associates it with the speci
   * fied Amazon CloudWatch metric
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html
   */
  PutMetricAlarm = 'cloudwatch:PutMetricAlarm',
  /**
   * Grants permission to publish metric data points to Amazon CloudWatch
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html
   */
  PutMetricData = 'cloudwatch:PutMetricData',
  /**
   * Grants permission to create a CloudWatch metric stream, or update an existing m
   * etric stream if it already exists
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricStream.html
   */
  PutMetricStream = 'cloudwatch:PutMetricStream',
  /**
   * Grants permission to temporarily set the state of an alarm for testing purposes
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_SetAlarmState.html
   */
  SetAlarmState = 'cloudwatch:SetAlarmState',
  /**
   * Grants permission to start all CloudWatch metric streams that you specify
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_StartMetricStreams.html
   */
  StartMetricStreams = 'cloudwatch:StartMetricStreams',
  /**
   * Grants permission to stop all CloudWatch metric streams that you specify
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_StopMetricStreams.html
   */
  StopMetricStreams = 'cloudwatch:StopMetricStreams',
  /**
   * Grants permission to add tags to an Amazon CloudWatch resource
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_TagResource.html
   */
  TagResource = 'cloudwatch:TagResource',
  /**
   * Grants permission to remove a tag from an Amazon CloudWatch resource
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'cloudwatch:UntagResource',
  /**
   * Grants permission to update a service level objective
   *
   * See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html#ApplicationSignals-PreviewSDK
   */
  UpdateServiceLevelObjective = 'cloudwatch:UpdateServiceLevelObjective',
}
