// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon CodeGuru (CODEGURU)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncodeguru.html
 *
 * 2025-02-24T21:47:15.344Z
 */
export enum AwsCodeguruActions {
  /**
   * Grants permission to get free trial summary for the CodeGuru service which incl
   * udes expiration date
   *
   * See https://docs.aws.amazon.com/codeguru/latest/profiler-api/API_GetCodeGuruFreeTrialSummary.html
   */
  GetCodeGuruFreeTrialSummary = 'codeguru:GetCodeGuruFreeTrialSummary',
}
