// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Comprehend (COMPREHEND)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncomprehend.html
 *
 * 2024-02-12T09:56:42.462Z
 */
export enum AwsComprehendActions {
  /**
   * Grants permission to detect the language or languages present in the list of te
   * xt documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectDominantLanguage.html
   */
  BatchDetectDominantLanguage = 'comprehend:BatchDetectDominantLanguage',
  /**
   * Grants permission to detect the named entities ("People", "Places", "Locations"
   * , etc) within the given list of text documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectEntities.html
   */
  BatchDetectEntities = 'comprehend:BatchDetectEntities',
  /**
   * Grants permission to detect the phrases in the list of text documents that are
   * most indicative of the content
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectKeyPhrases.html
   */
  BatchDetectKeyPhrases = 'comprehend:BatchDetectKeyPhrases',
  /**
   * Grants permission to detect the sentiment of a text in the list of documents (P
   * ositive, Negative, Neutral, or Mixed)
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectSentiment.html
   */
  BatchDetectSentiment = 'comprehend:BatchDetectSentiment',
  /**
   * Grants permission to detect syntactic information (like Part of Speech, Tokens)
   * in a list of text documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectSyntax.html
   */
  BatchDetectSyntax = 'comprehend:BatchDetectSyntax',
  /**
   * Grants permission to detect the sentiments associated with specific entities (s
   * uch as brands or products) within the given list of text documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_BatchDetectTargetedSentiment.html
   */
  BatchDetectTargetedSentiment = 'comprehend:BatchDetectTargetedSentiment',
  /**
   * Grants permission to create a new document classification request to analyze a
   * single document in real-time, using a previously created and trained custom mod
   * el and an endpoint
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ClassifyDocument.html
   */
  ClassifyDocument = 'comprehend:ClassifyDocument',
  /**
   * Grants permission to classify the personally identifiable information within gi
   * ven documents in real-time
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ContainsPiiEntities.html
   */
  ContainsPiiEntities = 'comprehend:ContainsPiiEntities',
  /**
   * Grants permission to create a new dataset within a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_CreateDataset.html
   */
  CreateDataset = 'comprehend:CreateDataset',
  /**
   * Grants permission to create a new document classifier that you can use to categ
   * orize documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_CreateDocumentClassifier.html
   */
  CreateDocumentClassifier = 'comprehend:CreateDocumentClassifier',
  /**
   * Grants permission to create a model-specific endpoint for synchronous inference
   * for a previously trained custom model
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_CreateEndpoint.html
   */
  CreateEndpoint = 'comprehend:CreateEndpoint',
  /**
   * Grants permission to create an entity recognizer using submitted files
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_CreateEntityRecognizer.html
   */
  CreateEntityRecognizer = 'comprehend:CreateEntityRecognizer',
  /**
   * Grants permission to create a new flywheel that you can use to train model vers
   * ions
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_CreateFlywheel.html
   */
  CreateFlywheel = 'comprehend:CreateFlywheel',
  /**
   * Grants permission to delete a previously created document classifier
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DeleteDocumentClassifier.html
   */
  DeleteDocumentClassifier = 'comprehend:DeleteDocumentClassifier',
  /**
   * Grants permission to delete a model-specific endpoint for a previously-trained
   * custom model. All endpoints must be deleted in order for the model to be delete
   * d
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DeleteEndpoint.html
   */
  DeleteEndpoint = 'comprehend:DeleteEndpoint',
  /**
   * Grants permission to delete a submitted entity recognizer
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DeleteEntityRecognizer.html
   */
  DeleteEntityRecognizer = 'comprehend:DeleteEntityRecognizer',
  /**
   * Grants permission to Delete a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DeleteFlywheel.html
   */
  DeleteFlywheel = 'comprehend:DeleteFlywheel',
  /**
   * Grants permission to remove policy on resource
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DeleteResourcePolicy.html
   */
  DeleteResourcePolicy = 'comprehend:DeleteResourcePolicy',
  /**
   * Grants permission to get the properties associated with a dataset
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeDataset.html
   */
  DescribeDataset = 'comprehend:DescribeDataset',
  /**
   * Grants permission to get the properties associated with a document classificati
   * on job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeDocumentClassificationJob.html
   */
  DescribeDocumentClassificationJob = 'comprehend:DescribeDocumentClassificationJob',
  /**
   * Grants permission to get the properties associated with a document classifier
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeDocumentClassifier.html
   */
  DescribeDocumentClassifier = 'comprehend:DescribeDocumentClassifier',
  /**
   * Grants permission to get the properties associated with a dominant language det
   * ection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeDominantLanguageDetectionJob.html
   */
  DescribeDominantLanguageDetectionJob = 'comprehend:DescribeDominantLanguageDetectionJob',
  /**
   * Grants permission to get the properties associated with a specific endpoint. Us
   * e this operation to get the status of an endpoint
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeEndpoint.html
   */
  DescribeEndpoint = 'comprehend:DescribeEndpoint',
  /**
   * Grants permission to get the properties associated with an entities detection j
   * ob
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeEntitiesDetectionJob.html
   */
  DescribeEntitiesDetectionJob = 'comprehend:DescribeEntitiesDetectionJob',
  /**
   * Grants permission to provide details about an entity recognizer including statu
   * s, S3 buckets containing training data, recognizer metadata, metrics, and so on
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeEntityRecognizer.html
   */
  DescribeEntityRecognizer = 'comprehend:DescribeEntityRecognizer',
  /**
   * Grants permission to get the properties associated with an Events detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeEventsDetectionJob.html
   */
  DescribeEventsDetectionJob = 'comprehend:DescribeEventsDetectionJob',
  /**
   * Grants permission to get the properties associated with a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeFlywheel.html
   */
  DescribeFlywheel = 'comprehend:DescribeFlywheel',
  /**
   * Grants permission to get the properties associated with a flywheel iteration fo
   * r a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeFlywheelIteration.html
   */
  DescribeFlywheelIteration = 'comprehend:DescribeFlywheelIteration',
  /**
   * Grants permission to get the properties associated with a key phrases detection
   * job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeKeyPhrasesDetectionJob.html
   */
  DescribeKeyPhrasesDetectionJob = 'comprehend:DescribeKeyPhrasesDetectionJob',
  /**
   * Grants permission to get the properties associated with a PII entities detectio
   * n job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribePiiEntitiesDetectionJob.html
   */
  DescribePiiEntitiesDetectionJob = 'comprehend:DescribePiiEntitiesDetectionJob',
  /**
   * Grants permission to read attached policy on resource
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeResourcePolicy.html
   */
  DescribeResourcePolicy = 'comprehend:DescribeResourcePolicy',
  /**
   * Grants permission to get the properties associated with a sentiment detection j
   * ob
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeSentimentDetectionJob.html
   */
  DescribeSentimentDetectionJob = 'comprehend:DescribeSentimentDetectionJob',
  /**
   * Grants permission to get the properties associated with a targeted sentiment de
   * tection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeTargetedSentimentDetectionJob.html
   */
  DescribeTargetedSentimentDetectionJob = 'comprehend:DescribeTargetedSentimentDetectionJob',
  /**
   * Grants permission to get the properties associated with a topic detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DescribeTopicsDetectionJob.html
   */
  DescribeTopicsDetectionJob = 'comprehend:DescribeTopicsDetectionJob',
  /**
   * Grants permission to detect the language or languages present in the text
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectDominantLanguage.html
   */
  DetectDominantLanguage = 'comprehend:DetectDominantLanguage',
  /**
   * Grants permission to detect the named entities ("People", "Places", "Locations"
   * , etc) within the given text document
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectEntities.html
   */
  DetectEntities = 'comprehend:DetectEntities',
  /**
   * Grants permission to detect the phrases in the text that are most indicative of
   * the content
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectKeyPhrases.html
   */
  DetectKeyPhrases = 'comprehend:DetectKeyPhrases',
  /**
   * Grants permission to detect the personally identifiable information entities ("
   * Name", "SSN", "PIN", etc) within the given text document
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectPiiEntities.html
   */
  DetectPiiEntities = 'comprehend:DetectPiiEntities',
  /**
   * Grants permission to detect the sentiment of a text in a document (Positive, Ne
   * gative, Neutral, or Mixed)
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectSentiment.html
   */
  DetectSentiment = 'comprehend:DetectSentiment',
  /**
   * Grants permission to detect syntactic information (like Part of Speech, Tokens)
   * in a text document
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectSyntax.html
   */
  DetectSyntax = 'comprehend:DetectSyntax',
  /**
   * Grants permission to detect the sentiments associated with specific entities (s
   * uch as brands or products) in a document
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectTargetedSentiment.html
   */
  DetectTargetedSentiment = 'comprehend:DetectTargetedSentiment',
  /**
   * Grants permission to detect toxic content within the given list of text segment
   * s
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_DetectToxicContent.html
   */
  DetectToxicContent = 'comprehend:DetectToxicContent',
  /**
   * Grants permission to import a trained Comprehend model
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ImportModel.html
   */
  ImportModel = 'comprehend:ImportModel',
  /**
   * Grants permission to get a list of the Datasets associated with a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListDatasets.html
   */
  ListDatasets = 'comprehend:ListDatasets',
  /**
   * Grants permission to get a list of the document classification jobs that you ha
   * ve submitted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListDocumentClassificationJobs.html
   */
  ListDocumentClassificationJobs = 'comprehend:ListDocumentClassificationJobs',
  /**
   * Grants permission to get a list of summaries of the document classifiers that y
   * ou have created
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListDocumentClassifierSummaries.html
   */
  ListDocumentClassifierSummaries = 'comprehend:ListDocumentClassifierSummaries',
  /**
   * Grants permission to get a list of the document classifiers that you have creat
   * ed
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListDocumentClassifiers.html
   */
  ListDocumentClassifiers = 'comprehend:ListDocumentClassifiers',
  /**
   * Grants permission to get a list of the dominant language detection jobs that yo
   * u have submitted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListDominantLanguageDetectionJobs.html
   */
  ListDominantLanguageDetectionJobs = 'comprehend:ListDominantLanguageDetectionJobs',
  /**
   * Grants permission to get a list of all existing endpoints that you've created
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListEndpoints.html
   */
  ListEndpoints = 'comprehend:ListEndpoints',
  /**
   * Grants permission to get a list of the entity detection jobs that you have subm
   * itted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListEntitiesDetectionJobs.html
   */
  ListEntitiesDetectionJobs = 'comprehend:ListEntitiesDetectionJobs',
  /**
   * Grants permission to get a list of summaries for the entity recognizers that yo
   * u have created
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListEntityRecognizerSummaries.html
   */
  ListEntityRecognizerSummaries = 'comprehend:ListEntityRecognizerSummaries',
  /**
   * Grants permission to get a list of the properties of all entity recognizers tha
   * t you created, including recognizers currently in training
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListEntityRecognizers.html
   */
  ListEntityRecognizers = 'comprehend:ListEntityRecognizers',
  /**
   * Grants permission to get a list of Events detection jobs that you have submitte
   * d
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListEventsDetectionJobs.html
   */
  ListEventsDetectionJobs = 'comprehend:ListEventsDetectionJobs',
  /**
   * Grants permission to get a list of iterations associated for a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListFlywheelIterationHistory.html
   */
  ListFlywheelIterationHistory = 'comprehend:ListFlywheelIterationHistory',
  /**
   * Grants permission to get a list of the flywheels that you have created
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListFlywheels.html
   */
  ListFlywheels = 'comprehend:ListFlywheels',
  /**
   * Grants permission to get a list of key phrase detection jobs that you have subm
   * itted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListKeyPhrasesDetectionJobs.html
   */
  ListKeyPhrasesDetectionJobs = 'comprehend:ListKeyPhrasesDetectionJobs',
  /**
   * Grants permission to get a list of PII entities detection jobs that you have su
   * bmitted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListPiiEntitiesDetectionJobs.html
   */
  ListPiiEntitiesDetectionJobs = 'comprehend:ListPiiEntitiesDetectionJobs',
  /**
   * Grants permission to get a list of sentiment detection jobs that you have submi
   * tted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListSentimentDetectionJobs.html
   */
  ListSentimentDetectionJobs = 'comprehend:ListSentimentDetectionJobs',
  /**
   * Grants permission to list tags for a resource
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'comprehend:ListTagsForResource',
  /**
   * Grants permission to get a list of targeted sentiment detection jobs that you h
   * ave submitted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListTargetedSentimentDetectionJobs.html
   */
  ListTargetedSentimentDetectionJobs = 'comprehend:ListTargetedSentimentDetectionJobs',
  /**
   * Grants permission to get a list of the topic detection jobs that you have submi
   * tted
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_ListTopicsDetectionJobs.html
   */
  ListTopicsDetectionJobs = 'comprehend:ListTopicsDetectionJobs',
  /**
   * Grants permission to attach policy to resource
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_PutResourcePolicy.html
   */
  PutResourcePolicy = 'comprehend:PutResourcePolicy',
  /**
   * Grants permission to start an asynchronous document classification job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartDocumentClassificationJob.html
   */
  StartDocumentClassificationJob = 'comprehend:StartDocumentClassificationJob',
  /**
   * Grants permission to start an asynchronous dominant language detection job for
   * a collection of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartDominantLanguageDetectionJob.html
   */
  StartDominantLanguageDetectionJob = 'comprehend:StartDominantLanguageDetectionJob',
  /**
   * Grants permission to start an asynchronous entity detection job for a collectio
   * n of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartEntitiesDetectionJob.html
   */
  StartEntitiesDetectionJob = 'comprehend:StartEntitiesDetectionJob',
  /**
   * Grants permission to start an asynchronous Events detection job for a collectio
   * n of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartEventsDetectionJob.html
   */
  StartEventsDetectionJob = 'comprehend:StartEventsDetectionJob',
  /**
   * Grants permission to start a flywheel iteration for a flywheel
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartFlywheelIteration.html
   */
  StartFlywheelIteration = 'comprehend:StartFlywheelIteration',
  /**
   * Grants permission to start an asynchronous key phrase detection job for a colle
   * ction of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartKeyPhrasesDetectionJob.html
   */
  StartKeyPhrasesDetectionJob = 'comprehend:StartKeyPhrasesDetectionJob',
  /**
   * Grants permission to start an asynchronous PII entities detection job for a col
   * lection of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartPiiEntitiesDetectionJob.html
   */
  StartPiiEntitiesDetectionJob = 'comprehend:StartPiiEntitiesDetectionJob',
  /**
   * Grants permission to start an asynchronous sentiment detection job for a collec
   * tion of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartSentimentDetectionJob.html
   */
  StartSentimentDetectionJob = 'comprehend:StartSentimentDetectionJob',
  /**
   * Grants permission to start an asynchronous targeted sentiment detection job for
   * a collection of documents
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartTargetedSentimentDetectionJob.html
   */
  StartTargetedSentimentDetectionJob = 'comprehend:StartTargetedSentimentDetectionJob',
  /**
   * Grants permission to start an asynchronous job to detect the most common topics
   * in the collection of documents and the phrases associated with each topic
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StartTopicsDetectionJob.html
   */
  StartTopicsDetectionJob = 'comprehend:StartTopicsDetectionJob',
  /**
   * Grants permission to stop a dominant language detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopDominantLanguageDetectionJob.html
   */
  StopDominantLanguageDetectionJob = 'comprehend:StopDominantLanguageDetectionJob',
  /**
   * Grants permission to stop an entity detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopEntitiesDetectionJob.html
   */
  StopEntitiesDetectionJob = 'comprehend:StopEntitiesDetectionJob',
  /**
   * Grants permission to stop an Events detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopEventsDetectionJob.html
   */
  StopEventsDetectionJob = 'comprehend:StopEventsDetectionJob',
  /**
   * Grants permission to stop a key phrase detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopKeyPhrasesDetectionJob.html
   */
  StopKeyPhrasesDetectionJob = 'comprehend:StopKeyPhrasesDetectionJob',
  /**
   * Grants permission to stop a PII entities detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopPiiEntitiesDetectionJob.html
   */
  StopPiiEntitiesDetectionJob = 'comprehend:StopPiiEntitiesDetectionJob',
  /**
   * Grants permission to stop a sentiment detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopSentimentDetectionJob.html
   */
  StopSentimentDetectionJob = 'comprehend:StopSentimentDetectionJob',
  /**
   * Grants permission to stop a targeted sentiment detection job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopTargetedSentimentDetectionJob.html
   */
  StopTargetedSentimentDetectionJob = 'comprehend:StopTargetedSentimentDetectionJob',
  /**
   * Grants permission to stop a previously created document classifier training job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopTrainingDocumentClassifier.html
   */
  StopTrainingDocumentClassifier = 'comprehend:StopTrainingDocumentClassifier',
  /**
   * Grants permission to stop a previously created entity recognizer training job
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_StopTrainingEntityRecognizer.html
   */
  StopTrainingEntityRecognizer = 'comprehend:StopTrainingEntityRecognizer',
  /**
   * Grants permission to tag a resource with given key value pairs
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_TagResource.html
   */
  TagResource = 'comprehend:TagResource',
  /**
   * Grants permission to untag a resource with given key
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'comprehend:UntagResource',
  /**
   * Grants permission to update information about the specified endpoint
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_UpdateEndpoint.html
   */
  UpdateEndpoint = 'comprehend:UpdateEndpoint',
  /**
   * Grants permission to Update a flywheel's configuration
   *
   * See https://docs.aws.amazon.com/comprehend/latest/APIReference/API_UpdateFlywheel.html
   */
  UpdateFlywheel = 'comprehend:UpdateFlywheel',
}
