// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Consolidated Billing (CONSOLIDATEDBILLING)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsconsolidatedbilling.html
 *
 * 2025-02-24T21:47:26.892Z
 */
export enum AwsConsolidatedbillingActions {
  /**
   * Grants permission to get account role (Payer, Linked, Regular)
   *
   * See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-permissions-ref.html
   */
  GetAccountBillingRole = 'consolidatedbilling:GetAccountBillingRole',
  /**
   * Grants permission to get list of member/linked accounts
   *
   * See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-permissions-ref.html
   */
  ListLinkedAccounts = 'consolidatedbilling:ListLinkedAccounts',
}
