// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Glue DataBrew (DATABREW)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsgluedatabrew.html
 *
 * 2024-02-12T09:57:31.892Z
 */
export enum AwsDatabrewActions {
  /**
   * Grants permission to delete one or more recipe versions
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_BatchDeleteRecipeVersion.html
   */
  BatchDeleteRecipeVersion = 'databrew:BatchDeleteRecipeVersion',
  /**
   * Grants permission to create a dataset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateDataset.html
   */
  CreateDataset = 'databrew:CreateDataset',
  /**
   * Grants permission to create a profile job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateProfileJob.html
   */
  CreateProfileJob = 'databrew:CreateProfileJob',
  /**
   * Grants permission to create a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateProject.html
   */
  CreateProject = 'databrew:CreateProject',
  /**
   * Grants permission to create a recipe
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateRecipe.html
   */
  CreateRecipe = 'databrew:CreateRecipe',
  /**
   * Grants permission to create a recipe job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateRecipeJob.html
   */
  CreateRecipeJob = 'databrew:CreateRecipeJob',
  /**
   * Grants permission to create a ruleset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateRuleset.html
   */
  CreateRuleset = 'databrew:CreateRuleset',
  /**
   * Grants permission to create a schedule
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_CreateSchedule.html
   */
  CreateSchedule = 'databrew:CreateSchedule',
  /**
   * Grants permission to delete a dataset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteDataset.html
   */
  DeleteDataset = 'databrew:DeleteDataset',
  /**
   * Grants permission to delete a job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteJob.html
   */
  DeleteJob = 'databrew:DeleteJob',
  /**
   * Grants permission to delete a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteProject.html
   */
  DeleteProject = 'databrew:DeleteProject',
  /**
   * Grants permission to delete a recipe version
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteRecipeVersion.html
   */
  DeleteRecipeVersion = 'databrew:DeleteRecipeVersion',
  /**
   * Grants permission to delete a ruleset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteRuleset.html
   */
  DeleteRuleset = 'databrew:DeleteRuleset',
  /**
   * Grants permission to delete a schedule
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DeleteSchedule.html
   */
  DeleteSchedule = 'databrew:DeleteSchedule',
  /**
   * Grants permission to view details about a dataset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeDataset.html
   */
  DescribeDataset = 'databrew:DescribeDataset',
  /**
   * Grants permission to view details about a job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeJob.html
   */
  DescribeJob = 'databrew:DescribeJob',
  /**
   * Grants permission to view details about job run for a given job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeJobRun.html
   */
  DescribeJobRun = 'databrew:DescribeJobRun',
  /**
   * Grants permission to view details about a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeProject.html
   */
  DescribeProject = 'databrew:DescribeProject',
  /**
   * Grants permission to view details about a recipe
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeRecipe.html
   */
  DescribeRecipe = 'databrew:DescribeRecipe',
  /**
   * Grants permission to view details about a ruleset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeRuleset.html
   */
  DescribeRuleset = 'databrew:DescribeRuleset',
  /**
   * Grants permission to view details about a schedule
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_DescribeSchedule.html
   */
  DescribeSchedule = 'databrew:DescribeSchedule',
  /**
   * Grants permission to list datasets in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListDatasets.html
   */
  ListDatasets = 'databrew:ListDatasets',
  /**
   * Grants permission to list job runs for a given job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListJobRuns.html
   */
  ListJobRuns = 'databrew:ListJobRuns',
  /**
   * Grants permission to list jobs in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListJobs.html
   */
  ListJobs = 'databrew:ListJobs',
  /**
   * Grants permission to list projects in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListProjects.html
   */
  ListProjects = 'databrew:ListProjects',
  /**
   * Grants permission to list versions in your recipe
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListRecipeVersions.html
   */
  ListRecipeVersions = 'databrew:ListRecipeVersions',
  /**
   * Grants permission to list recipes in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListRecipes.html
   */
  ListRecipes = 'databrew:ListRecipes',
  /**
   * Grants permission to list rulesets in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListRulesets.html
   */
  ListRulesets = 'databrew:ListRulesets',
  /**
   * Grants permission to list schedules in your account
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListSchedules.html
   */
  ListSchedules = 'databrew:ListSchedules',
  /**
   * Grants permission to retrieve tags associated with a resource
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_ListTagsForResource.html
   */
  ListTagsForResource = 'databrew:ListTagsForResource',
  /**
   * Grants permission to publish a major verison of a recipe
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_PublishRecipe.html
   */
  PublishRecipe = 'databrew:PublishRecipe',
  /**
   * Grants permission to submit an action to the interactive session for a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_SendProjectSessionAction.html
   */
  SendProjectSessionAction = 'databrew:SendProjectSessionAction',
  /**
   * Grants permission to start running a job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_StartJobRun.html
   */
  StartJobRun = 'databrew:StartJobRun',
  /**
   * Grants permission to start an interactive session for a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_StartProjectSession.html
   */
  StartProjectSession = 'databrew:StartProjectSession',
  /**
   * Grants permission to stop a job run for a job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_StopJobRun.html
   */
  StopJobRun = 'databrew:StopJobRun',
  /**
   * Grants permission to add tags to a resource
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_TagResource.html
   */
  TagResource = 'databrew:TagResource',
  /**
   * Grants permission to remove tags associated with a resource
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UntagResource.html
   */
  UntagResource = 'databrew:UntagResource',
  /**
   * Grants permission to modify a dataset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateDataset.html
   */
  UpdateDataset = 'databrew:UpdateDataset',
  /**
   * Grants permission to modify a profile job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateProfileJob.html
   */
  UpdateProfileJob = 'databrew:UpdateProfileJob',
  /**
   * Grants permission to modify a project
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateProject.html
   */
  UpdateProject = 'databrew:UpdateProject',
  /**
   * Grants permission to modify a recipe
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateRecipe.html
   */
  UpdateRecipe = 'databrew:UpdateRecipe',
  /**
   * Grants permission to modify a recipe job
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateRecipeJob.html
   */
  UpdateRecipeJob = 'databrew:UpdateRecipeJob',
  /**
   * Grants permission to modify a ruleset
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateRuleset.html
   */
  UpdateRuleset = 'databrew:UpdateRuleset',
  /**
   * Grants permission to modify a schedule
   *
   * See https://docs.aws.amazon.com/databrew/latest/dg/API_UpdateSchedule.html
   */
  UpdateSchedule = 'databrew:UpdateSchedule',
}
