// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS DeepRacer (DEEPRACER)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsdeepracer.html
 *
 * 2024-02-12T09:56:56.343Z
 */
export enum AwsDeepracerActions {
  /**
   * Grants permission to add access for a private leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-manage-community-races.html
   */
  AddLeaderboardAccessPermission = 'deepracer:AddLeaderboardAccessPermission',
  /**
   * Grants permission to get current admin multiuser configuration for this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-set-account-config.html
   */
  AdminGetAccountConfig = 'deepracer:AdminGetAccountConfig',
  /**
   * Grants permission to list all deepracer users with their associated resources c
   * reated under this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-list-associated-resources.html
   */
  AdminListAssociatedResources = 'deepracer:AdminListAssociatedResources',
  /**
   * Grants permission to list user data for all users associated with this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-list-associated-users.html
   */
  AdminListAssociatedUsers = 'deepracer:AdminListAssociatedUsers',
  /**
   * Grants permission to manage a user associated with this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-manage-user.html
   */
  AdminManageUser = 'deepracer:AdminManageUser',
  /**
   * Grants permission to set configuration options for this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-set-account-config.html
   */
  AdminSetAccountConfig = 'deepracer:AdminSetAccountConfig',
  /**
   * Grants permission to clone an existing DeepRacer model
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-console-train-evaluate-models.html#deepracer-clone-trained-model
   */
  CloneReinforcementLearningModel = 'deepracer:CloneReinforcementLearningModel',
  /**
   * Grants permission to create a DeepRacer car in your garage
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-choose-race-type.html
   */
  CreateCar = 'deepracer:CreateCar',
  /**
   * Grants permission to create a leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-create-community-race.html
   */
  CreateLeaderboard = 'deepracer:CreateLeaderboard',
  /**
   * Grants permission to create an access token for a private leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-manage-community-races.html
   */
  CreateLeaderboardAccessToken = 'deepracer:CreateLeaderboardAccessToken',
  /**
   * Grants permission to submit a DeepRacer model to be evaluated for leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  CreateLeaderboardSubmission = 'deepracer:CreateLeaderboardSubmission',
  /**
   * Grants permission to create ra einforcement learning model for DeepRacer
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  CreateReinforcementLearningModel = 'deepracer:CreateReinforcementLearningModel',
  /**
   * Grants permission to delete a leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-manage-community-races.html
   */
  DeleteLeaderboard = 'deepracer:DeleteLeaderboard',
  /**
   * Grants permission to delete a DeepRacer model
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  DeleteModel = 'deepracer:DeleteModel',
  /**
   * Grants permission to edit a leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-manage-community-races.html
   */
  EditLeaderboard = 'deepracer:EditLeaderboard',
  /**
   * Grants permission to get current multiuser configuration for this account
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-admin-set-account-config.html
   */
  GetAccountConfig = 'deepracer:GetAccountConfig',
  /**
   * Grants permission to retrieve the user's alias for submitting a DeepRacer model
   * to leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  GetAlias = 'deepracer:GetAlias',
  /**
   * Grants permission to download artifacts for an existing DeepRacer model
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-console-train-evaluate-models.html
   */
  GetAssetUrl = 'deepracer:GetAssetUrl',
  /**
   * Grants permission to retrieve a specific DeepRacer car from your garage
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-choose-race-type.html
   */
  GetCar = 'deepracer:GetCar',
  /**
   * Grants permission to view all the DeepRacer cars in your garage
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-choose-race-type.html
   */
  GetCars = 'deepracer:GetCars',
  /**
   * Grants permission to retrieve information about an existing DeepRacer model's e
   * valuation jobs
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-test-in-simulator.html
   */
  GetEvaluation = 'deepracer:GetEvaluation',
  /**
   * Grants permission to retrieve information about how the latest submitted DeepRa
   * cer model for a user performed on a leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  GetLatestUserSubmission = 'deepracer:GetLatestUserSubmission',
  /**
   * Grants permission to retrieve information about leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  GetLeaderboard = 'deepracer:GetLeaderboard',
  /**
   * Grants permission to retrieve information about an existing DeepRacer model
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  GetModel = 'deepracer:GetModel',
  /**
   * Grants permission to retrieve information about private leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-join-community-race.html
   */
  GetPrivateLeaderboard = 'deepracer:GetPrivateLeaderboard',
  /**
   * Grants permission to retrieve information about the performance of a user's Dee
   * pRacer model that got placed on a leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  GetRankedUserSubmission = 'deepracer:GetRankedUserSubmission',
  /**
   * Grants permission to retrieve information about DeepRacer tracks
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-console-train-evaluate-models.html
   */
  GetTrack = 'deepracer:GetTrack',
  /**
   * Grants permission to retrieve information about an existing DeepRacer model's t
   * raining job
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  GetTrainingJob = 'deepracer:GetTrainingJob',
  /**
   * Grants permission to import a reinforcement learning model for DeepRacer
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-troubleshooting-service-migration-errors.html
   */
  ImportModel = 'deepracer:ImportModel',
  /**
   * Grants permission to list a DeepRacer model's evaluation jobs
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-test-in-simulator.html
   */
  ListEvaluations = 'deepracer:ListEvaluations',
  /**
   * Grants permission to list all the user's leaderboard evaluation jobs for a lead
   * erboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  ListLeaderboardEvaluations = 'deepracer:ListLeaderboardEvaluations',
  /**
   * Grants permission to list all the DeepRacer model submissions of a user on a le
   * aderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  ListLeaderboardSubmissions = 'deepracer:ListLeaderboardSubmissions',
  /**
   * Grants permission to list all the available leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  ListLeaderboards = 'deepracer:ListLeaderboards',
  /**
   * Grants permission to list all existing DeepRacer models
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  ListModels = 'deepracer:ListModels',
  /**
   * Grants permission to retrieve participant information about private leaderboard
   * s
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-join-community-race.html
   */
  ListPrivateLeaderboardParticipants = 'deepracer:ListPrivateLeaderboardParticipants',
  /**
   * Grants permission to list all the available private leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-join-community-race.html
   */
  ListPrivateLeaderboards = 'deepracer:ListPrivateLeaderboards',
  /**
   * Grants permission to list all the subscribed private leaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-join-community-race.html
   */
  ListSubscribedPrivateLeaderboards = 'deepracer:ListSubscribedPrivateLeaderboards',
  /**
   * Grants permission to lists tag for a resource
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-tagging.html
   */
  ListTagsForResource = 'deepracer:ListTagsForResource',
  /**
   * Grants permission to list all DeepRacer tracks
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-console-train-evaluate-models.html
   */
  ListTracks = 'deepracer:ListTracks',
  /**
   * Grants permission to list a DeepRacer model's training jobs
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  ListTrainingJobs = 'deepracer:ListTrainingJobs',
  /**
   * Grants permission to migrate previous reinforcement learning models for DeepRac
   * er
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-troubleshooting-service-migration-errors.html
   */
  MigrateModels = 'deepracer:MigrateModels',
  /**
   * Grants permission to performs the leaderboard operation mentioned in the operat
   * ion attribute
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-perform-leaderboard-operation.html
   */
  PerformLeaderboardOperation = 'deepracer:PerformLeaderboardOperation',
  /**
   * Grants permission to remove access for a private leaderboard
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-manage-community-races.html
   */
  RemoveLeaderboardAccessPermission = 'deepracer:RemoveLeaderboardAccessPermission',
  /**
   * Grants permission to set the user's alias for submitting a DeepRacer model to l
   * eaderboards
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-submit-model-to-leaderboard.html
   */
  SetAlias = 'deepracer:SetAlias',
  /**
   * Grants permission to evaluate a DeepRacer model in a simulated environment
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-test-in-simulator.html
   */
  StartEvaluation = 'deepracer:StartEvaluation',
  /**
   * Grants permission to stop DeepRacer model evaluations
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-test-in-simulator.html
   */
  StopEvaluation = 'deepracer:StopEvaluation',
  /**
   * Grants permission to stop training a DeepRacer model
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-get-started-training-model.html
   */
  StopTrainingReinforcementLearningModel = 'deepracer:StopTrainingReinforcementLearningModel',
  /**
   * Grants permission to tag a resource
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-tagging.html
   */
  TagResource = 'deepracer:TagResource',
  /**
   * Grants permission to test reward functions for correctness
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-console-train-evaluate-models.html#deepracer-train-models-define-reward-function
   */
  TestRewardFunction = 'deepracer:TestRewardFunction',
  /**
   * Grants permission to untag a resource
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-tagging.html
   */
  UntagResource = 'deepracer:UntagResource',
  /**
   * Grants permission to update a DeepRacer car in your garage
   *
   * See https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-choose-race-type.html
   */
  UpdateCar = 'deepracer:UpdateCar',
}
