// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Data Lifecycle Manager (DLM)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondatalifecyclemanager.html
 *
 * 2024-02-12T09:56:51.778Z
 */
export enum AwsDlmActions {
  /**
   * Grants permission to create a data lifecycle policy to manage the scheduled cre
   * ation and retention of Amazon EBS snapshots. You may have up to 100 policies
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html
   */
  CreateLifecyclePolicy = 'dlm:CreateLifecyclePolicy',
  /**
   * Grants permission to delete an existing data lifecycle policy. In addition, thi
   * s action halts the creation and deletion of snapshots that the policy specified
   * . Existing snapshots are not affected
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_DeleteLifecyclePolicy.html
   */
  DeleteLifecyclePolicy = 'dlm:DeleteLifecyclePolicy',
  /**
   * Grants permission to returns a list of summary descriptions of data lifecycle p
   * olicies
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_GetLifecyclePolicies.html
   */
  GetLifecyclePolicies = 'dlm:GetLifecyclePolicies',
  /**
   * Grants permission to return a complete description of a single data lifecycle p
   * olicy
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_GetLifecyclePolicy.html
   */
  GetLifecyclePolicy = 'dlm:GetLifecyclePolicy',
  /**
   * Grants permission to list the tags associated with a resource
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'dlm:ListTagsForResource',
  /**
   * Grants permission to add or update tags of a resource
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_TagResource.html
   */
  TagResource = 'dlm:TagResource',
  /**
   * Grants permission to remove tags associated with a resource
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'dlm:UntagResource',
  /**
   * Grants permission to update an existing data lifecycle policy
   *
   * See https://docs.aws.amazon.com/dlm/latest/APIReference/API_UpdateLifecyclePolicy.html
   */
  UpdateLifecyclePolicy = 'dlm:UpdateLifecyclePolicy',
}
