// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon DocumentDB Elastic Clusters (DOCDB-ELASTIC)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondocumentdbelasticclusters.html
 *
 * 2024-02-12T09:57:00.292Z
 */
export enum AwsDocdbElasticActions {
  /**
   * Grants permission to create a new Amazon DocDB-Elastic cluster
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_CreateCluster.html
   */
  CreateCluster = 'docdb-elastic:CreateCluster',
  /**
   * Grants permission to create a new Amazon DocDB-Elastic cluster snapshot
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_CreateClusterSnapshot.html
   */
  CreateClusterSnapshot = 'docdb-elastic:CreateClusterSnapshot',
  /**
   * Grants permission to delete a cluster
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_DeleteCluster.html
   */
  DeleteCluster = 'docdb-elastic:DeleteCluster',
  /**
   * Grants permission to delete a cluster snapshot
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_DeleteClusterSnapshot.html
   */
  DeleteClusterSnapshot = 'docdb-elastic:DeleteClusterSnapshot',
  /**
   * Grants permission to view details about a cluster
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_GetCluster.html
   */
  GetCluster = 'docdb-elastic:GetCluster',
  /**
   * Grants permission to view details about a cluster snapshot
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_GetClusterSnapshot.html
   */
  GetClusterSnapshot = 'docdb-elastic:GetClusterSnapshot',
  /**
   * Grants permission to list the cluster snapshots in your account
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_ListClusterSnapshots.html
   */
  ListClusterSnapshots = 'docdb-elastic:ListClusterSnapshots',
  /**
   * Grants permission to list the clusters in your account
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_ListClusters.html
   */
  ListClusters = 'docdb-elastic:ListClusters',
  /**
   * Grants permission to lists tag for an DocumentDB Elastic resource
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_ListTagsForResource.html
   */
  ListTagsForResource = 'docdb-elastic:ListTagsForResource',
  /**
   * Grants permission to restore cluster from a Amazon DocDB-Elastic cluster snapsh
   * ot
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_RestoreClusterFromSnapshot.html
   */
  RestoreClusterFromSnapshot = 'docdb-elastic:RestoreClusterFromSnapshot',
  /**
   * Grants permission to tag an DocumentDB Elastic resource
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_TagResource.html
   */
  TagResource = 'docdb-elastic:TagResource',
  /**
   * Grants permission to untag a DocumentDB Elastic resource
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_UntagResource.html
   */
  UntagResource = 'docdb-elastic:UntagResource',
  /**
   * Grants permission to modify a cluster
   *
   * See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_UpdateCluster.html
   */
  UpdateCluster = 'docdb-elastic:UpdateCluster',
}
