// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Directory Service Data (DS-DATA)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsdirectoryservicedata.html
 *
 * 2025-02-24T21:47:38.914Z
 */
export enum AwsDsDataActions {
  /**
   * Grants permission to add a member to a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_AddGroupMember.html
   */
  AddGroupMember = 'ds-data:AddGroupMember',
  /**
   * Grants permission to create a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_CreateGroup.html
   */
  CreateGroup = 'ds-data:CreateGroup',
  /**
   * Grants permission to create a user on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_CreateUser.html
   */
  CreateUser = 'ds-data:CreateUser',
  /**
   * Grants permission to delete a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_DeleteGroup.html
   */
  DeleteGroup = 'ds-data:DeleteGroup',
  /**
   * Grants permission to delete a user on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_DeleteUser.html
   */
  DeleteUser = 'ds-data:DeleteUser',
  /**
   * Grants permission to describe a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_DescribeGroup.html
   */
  DescribeGroup = 'ds-data:DescribeGroup',
  /**
   * Grants permission to describe a user on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_DescribeUser.html
   */
  DescribeUser = 'ds-data:DescribeUser',
  /**
   * Grants permission to disable a user on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_DisableUser.html
   */
  DisableUser = 'ds-data:DisableUser',
  /**
   * Grants permission to list members in a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_ListGroupMembers.html
   */
  ListGroupMembers = 'ds-data:ListGroupMembers',
  /**
   * Grants permission to list groups on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_ListGroups.html
   */
  ListGroups = 'ds-data:ListGroups',
  /**
   * Grants permission to list the groups that a member is in on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_ListGroupsForMember.html
   */
  ListGroupsForMember = 'ds-data:ListGroupsForMember',
  /**
   * Grants permission to list users on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_ListUsers.html
   */
  ListUsers = 'ds-data:ListUsers',
  /**
   * Grants permission to remove a member from a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_RemoveGroupMember.html
   */
  RemoveGroupMember = 'ds-data:RemoveGroupMember',
  /**
   * Grants permission to search for groups on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_SearchGroups.html
   */
  SearchGroups = 'ds-data:SearchGroups',
  /**
   * Grants permission to search for users on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_SearchUsers.html
   */
  SearchUsers = 'ds-data:SearchUsers',
  /**
   * Grants permission to update a group on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_UpdateGroup.html
   */
  UpdateGroup = 'ds-data:UpdateGroup',
  /**
   * Grants permission to update a user on a directory
   *
   * See https://docs.aws.amazon.com/directoryservicedata/latest/DirectoryServiceDataAPIReference/API_UpdateUser.html
   */
  UpdateUser = 'ds-data:UpdateUser',
}
