// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Elastic Block Store (EBS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticblockstore.html
 *
 * 2024-02-12T09:57:06.633Z
 */
export enum AwsEbsActions {
  /**
   * Grants permission to seal and complete the snapshot after all of the required b
   * locks of data have been written to it
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_CompleteSnapshot.html
   */
  CompleteSnapshot = 'ebs:CompleteSnapshot',
  /**
   * Grants permission to return the data of a block in an Amazon Elastic Block Stor
   * e (EBS) snapshot
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_GetSnapshotBlock.html
   */
  GetSnapshotBlock = 'ebs:GetSnapshotBlock',
  /**
   * Grants permission to list the blocks that are different between two Amazon Elas
   * tic Block Store (EBS) snapshots of the same volume/snapshot lineage
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_ListChangedBlocks.html
   */
  ListChangedBlocks = 'ebs:ListChangedBlocks',
  /**
   * Grants permission to list the blocks in an Amazon Elastic Block Store (EBS) sna
   * pshot
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_ListSnapshotBlocks.html
   */
  ListSnapshotBlocks = 'ebs:ListSnapshotBlocks',
  /**
   * Grants permission to write a block of data to a snapshot created by the StartSn
   * apshot operation
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_PutSnapshotBlock.html
   */
  PutSnapshotBlock = 'ebs:PutSnapshotBlock',
  /**
   * Grants permission to create a new EBS snapshot
   *
   * See https://docs.aws.amazon.com/ebs/latest/APIReference/API_StartSnapshot.html
   */
  StartSnapshot = 'ebs:StartSnapshot',
}
