// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Elastic Beanstalk (ELASTICBEANSTALK)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awselasticbeanstalk.html
 *
 * 2024-02-12T09:57:06.140Z
 */
export enum AwsElasticbeanstalkActions {
  /**
   * Grants permission to cancel in-progress environment configuration update or app
   * lication version deployment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_AbortEnvironmentUpdate.html
   */
  AbortEnvironmentUpdate = 'elasticbeanstalk:AbortEnvironmentUpdate',
  /**
   * Grants permission to add tags to an Elastic Beanstalk resource and to update ta
   * g values
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateTagsForResource.html
   */
  AddTags = 'elasticbeanstalk:AddTags',
  /**
   * Grants permission to apply a scheduled managed action immediately
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ApplyEnvironmentManagedAction.html
   */
  ApplyEnvironmentManagedAction = 'elasticbeanstalk:ApplyEnvironmentManagedAction',
  /**
   * Grants permission to associate an operations role with an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_AssociateEnvironmentOperationsRole.html
   */
  AssociateEnvironmentOperationsRole = 'elasticbeanstalk:AssociateEnvironmentOperationsRole',
  /**
   * Grants permission to check CNAME availability
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CheckDNSAvailability.html
   */
  CheckDNSAvailability = 'elasticbeanstalk:CheckDNSAvailability',
  /**
   * Grants permission to create or update a group of environments, each running a s
   * eparate component of a single application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ComposeEnvironments.html
   */
  ComposeEnvironments = 'elasticbeanstalk:ComposeEnvironments',
  /**
   * Grants permission to create a new application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateApplication.html
   */
  CreateApplication = 'elasticbeanstalk:CreateApplication',
  /**
   * Grants permission to create an application version for an application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateApplicationVersion.html
   */
  CreateApplicationVersion = 'elasticbeanstalk:CreateApplicationVersion',
  /**
   * Grants permission to create a configuration template
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateConfigurationTemplate.html
   */
  CreateConfigurationTemplate = 'elasticbeanstalk:CreateConfigurationTemplate',
  /**
   * Grants permission to launch an environment for an application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateEnvironment.html
   */
  CreateEnvironment = 'elasticbeanstalk:CreateEnvironment',
  /**
   * Grants permission to create a new version of a custom platform
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreatePlatformVersion.html
   */
  CreatePlatformVersion = 'elasticbeanstalk:CreatePlatformVersion',
  /**
   * Grants permission to create the Amazon S3 storage location for the account
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateStorageLocation.html
   */
  CreateStorageLocation = 'elasticbeanstalk:CreateStorageLocation',
  /**
   * Grants permission to delete an application along with all associated versions a
   * nd configurations
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DeleteApplication.html
   */
  DeleteApplication = 'elasticbeanstalk:DeleteApplication',
  /**
   * Grants permission to delete an application version from an application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DeleteApplicationVersion.html
   */
  DeleteApplicationVersion = 'elasticbeanstalk:DeleteApplicationVersion',
  /**
   * Grants permission to delete a configuration template
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DeleteConfigurationTemplate.html
   */
  DeleteConfigurationTemplate = 'elasticbeanstalk:DeleteConfigurationTemplate',
  /**
   * Grants permission to delete the draft configuration associated with the running
   * environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DeleteEnvironmentConfiguration.html
   */
  DeleteEnvironmentConfiguration = 'elasticbeanstalk:DeleteEnvironmentConfiguration',
  /**
   * Grants permission to delete a version of a custom platform
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DeletePlatformVersion.html
   */
  DeletePlatformVersion = 'elasticbeanstalk:DeletePlatformVersion',
  /**
   * Grants permission to retrieve a list of account attributes, including resource
   * quotas
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeAccountAttributes.html
   */
  DescribeAccountAttributes = 'elasticbeanstalk:DescribeAccountAttributes',
  /**
   * Grants permission to retrieve a list of application versions stored in an AWS E
   * lastic Beanstalk storage bucket
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeApplicationVersions.html
   */
  DescribeApplicationVersions = 'elasticbeanstalk:DescribeApplicationVersions',
  /**
   * Grants permission to retrieve the descriptions of existing applications
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeApplications.html
   */
  DescribeApplications = 'elasticbeanstalk:DescribeApplications',
  /**
   * Grants permission to retrieve descriptions of environment configuration options
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeConfigurationOptions.html
   */
  DescribeConfigurationOptions = 'elasticbeanstalk:DescribeConfigurationOptions',
  /**
   * Grants permission to retrieve a description of the settings for a configuration
   * set
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeConfigurationSettings.html
   */
  DescribeConfigurationSettings = 'elasticbeanstalk:DescribeConfigurationSettings',
  /**
   * Grants permission to retrieve information about the overall health of an enviro
   * nment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEnvironmentHealth.html
   */
  DescribeEnvironmentHealth = 'elasticbeanstalk:DescribeEnvironmentHealth',
  /**
   * Grants permission to retrieve a list of an environment's completed and failed m
   * anaged actions
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEnvironmentManagedActionHistory.html
   */
  DescribeEnvironmentManagedActionHistory = 'elasticbeanstalk:DescribeEnvironmentManagedActionHistory',
  /**
   * Grants permission to retrieve a list of an environment's upcoming and in-progre
   * ss managed actions
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEnvironmentManagedActions.html
   */
  DescribeEnvironmentManagedActions = 'elasticbeanstalk:DescribeEnvironmentManagedActions',
  /**
   * Grants permission to retrieve a list of AWS resources for an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEnvironmentResources.html
   */
  DescribeEnvironmentResources = 'elasticbeanstalk:DescribeEnvironmentResources',
  /**
   * Grants permission to retrieve descriptions for existing environments
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEnvironments.html
   */
  DescribeEnvironments = 'elasticbeanstalk:DescribeEnvironments',
  /**
   * Grants permission to retrieve a list of event descriptions matching a set of cr
   * iteria
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeEvents.html
   */
  DescribeEvents = 'elasticbeanstalk:DescribeEvents',
  /**
   * Grants permission to retrieve more detailed information about the health of env
   * ironment instances
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribeInstancesHealth.html
   */
  DescribeInstancesHealth = 'elasticbeanstalk:DescribeInstancesHealth',
  /**
   * Grants permission to retrieve a description of a managed platform version
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DescribePlatformVersion.html
   */
  DescribePlatformVersion = 'elasticbeanstalk:DescribePlatformVersion',
  /**
   * Grants permission to disassociate an operations role with an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_DisassociateEnvironmentOperationsRole.html
   */
  DisassociateEnvironmentOperationsRole = 'elasticbeanstalk:DisassociateEnvironmentOperationsRole',
  /**
   * Grants permission to retrieve a list of the available solution stack names
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ListAvailableSolutionStacks.html
   */
  ListAvailableSolutionStacks = 'elasticbeanstalk:ListAvailableSolutionStacks',
  /**
   * Grants permission to retrieve a list of the available platform branches
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ListPlatformBranches.html
   */
  ListPlatformBranches = 'elasticbeanstalk:ListPlatformBranches',
  /**
   * Grants permission to retrieve a list of the available platforms
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ListPlatformVersions.html
   */
  ListPlatformVersions = 'elasticbeanstalk:ListPlatformVersions',
  /**
   * Grants permission to retrieve a list of tags of an Elastic Beanstalk resource
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ListTagsForResource.html
   */
  ListTagsForResource = 'elasticbeanstalk:ListTagsForResource',
  /**
   * Grants permission to submit instance statistics for enhanced health
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced.html#health-enhanced-authz
   */
  PutInstanceStatistics = 'elasticbeanstalk:PutInstanceStatistics',
  /**
   * Grants permission to delete and recreate all of the AWS resources for an enviro
   * nment and to force a restart
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_RebuildEnvironment.html
   */
  RebuildEnvironment = 'elasticbeanstalk:RebuildEnvironment',
  /**
   * Grants permission to remove tags from an Elastic Beanstalk resource
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateTagsForResource.html
   */
  RemoveTags = 'elasticbeanstalk:RemoveTags',
  /**
   * Grants permission to initiate a request to compile information of the deployed
   * environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_RequestEnvironmentInfo.html
   */
  RequestEnvironmentInfo = 'elasticbeanstalk:RequestEnvironmentInfo',
  /**
   * Grants permission to request an environment to restart the application containe
   * r server running on each Amazon EC2 instance
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_RestartAppServer.html
   */
  RestartAppServer = 'elasticbeanstalk:RestartAppServer',
  /**
   * Grants permission to retrieve the compiled information from a RequestEnvironmen
   * tInfo request
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_RetrieveEnvironmentInfo.html
   */
  RetrieveEnvironmentInfo = 'elasticbeanstalk:RetrieveEnvironmentInfo',
  /**
   * Grants permission to swap the CNAMEs of two environments
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_SwapEnvironmentCNAMEs.html
   */
  SwapEnvironmentCNAMEs = 'elasticbeanstalk:SwapEnvironmentCNAMEs',
  /**
   * Grants permission to terminate an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_TerminateEnvironment.html
   */
  TerminateEnvironment = 'elasticbeanstalk:TerminateEnvironment',
  /**
   * Grants permission to update an application with specified properties
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateApplication.html
   */
  UpdateApplication = 'elasticbeanstalk:UpdateApplication',
  /**
   * Grants permission to update the application version lifecycle policy associated
   * with the application
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateApplicationResourceLifecycle.html
   */
  UpdateApplicationResourceLifecycle = 'elasticbeanstalk:UpdateApplicationResourceLifecycle',
  /**
   * Grants permission to update an application version with specified properties
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateApplicationVersion.html
   */
  UpdateApplicationVersion = 'elasticbeanstalk:UpdateApplicationVersion',
  /**
   * Grants permission to update a configuration template with specified properties
   * or configuration option values
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateConfigurationTemplate.html
   */
  UpdateConfigurationTemplate = 'elasticbeanstalk:UpdateConfigurationTemplate',
  /**
   * Grants permission to update an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateEnvironment.html
   */
  UpdateEnvironment = 'elasticbeanstalk:UpdateEnvironment',
  /**
   * Grants permission to add tags to an Elastic Beanstalk resource, remove tags, an
   * d to update tag values
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateTagsForResource.html
   */
  UpdateTagsForResource = 'elasticbeanstalk:UpdateTagsForResource',
  /**
   * Grants permission to check the validity of a set of configuration settings for
   * a configuration template or an environment
   *
   * See https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ValidateConfigurationSettings.html
   */
  ValidateConfigurationSettings = 'elasticbeanstalk:ValidateConfigurationSettings',
}
