// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon FinSpace API (FINSPACE-API)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonfinspaceapi.html
 *
 * 2024-02-12T09:57:25.916Z
 */
export enum AwsFinspaceApiActions {
  /**
   * Grants permission to retrieve FinSpace programmatic access credentials
   *
   * See https://docs.aws.amazon.com/finspace/latest/data-api/API_GetProgrammaticAccessCredentials.html
   */
  GetProgrammaticAccessCredentials = 'finspace-api:GetProgrammaticAccessCredentials',
}
