// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon FSx (FSX)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonfsx.html
 *
 * 2025-02-24T21:48:06.017Z
 */
export enum AwsFsxActions {
  /**
   * Grants permission to associate a File Gateway instance with an Amazon FSx for W
   * indows File Server file system
   *
   * See https://docs.aws.amazon.com/filegateway/latest/filefsxw/what-is-file-fsxw.html
   */
  AssociateFileGateway = 'fsx:AssociateFileGateway',
  /**
   * Grants permission to associate DNS aliases with an Amazon FSx for Windows File
   * Server file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_AssociateFileSystemAliases.html
   */
  AssociateFileSystemAliases = 'fsx:AssociateFileSystemAliases',
  /**
   * Grants permission to allow deletion of an FSx for ONTAP SnapLock Enterprise vol
   * ume that contains WORM (write once, read many) files with active retention peri
   * ods
   *
   * See https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/snaplock-enterprise.html#bypass-enterprise
   */
  BypassSnaplockEnterpriseRetention = 'fsx:BypassSnaplockEnterpriseRetention',
  /**
   * Grants permission to cancel a data repository task
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CancelDataRepositoryTask.html
   */
  CancelDataRepositoryTask = 'fsx:CancelDataRepositoryTask',
  /**
   * Grants permission to copy a backup
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CopyBackup.html
   */
  CopyBackup = 'fsx:CopyBackup',
  /**
   * Grants permission to update an existing volume by using a snapshot from another
   * Amazon FSx for OpenZFS file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CopySnapshotAndUpdateVolume.html
   */
  CopySnapshotAndUpdateVolume = 'fsx:CopySnapshotAndUpdateVolume',
  /**
   * Grants permission to create a new backup of an Amazon FSx file system or an Ama
   * zon FSx volume
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateBackup.html
   */
  CreateBackup = 'fsx:CreateBackup',
  /**
   * Grants permission to create a new data respository association for an Amazon FS
   * x for Lustre file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateDataRepositoryAssociation.html
   */
  CreateDataRepositoryAssociation = 'fsx:CreateDataRepositoryAssociation',
  /**
   * Grants permission to create a new data respository task for an Amazon FSx for L
   * ustre file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateDataRepositoryTask.html
   */
  CreateDataRepositoryTask = 'fsx:CreateDataRepositoryTask',
  /**
   * Grants permission to create a new, empty, Amazon file cache
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileCache.html
   */
  CreateFileCache = 'fsx:CreateFileCache',
  /**
   * Grants permission to create a new, empty, Amazon FSx file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystem.html
   */
  CreateFileSystem = 'fsx:CreateFileSystem',
  /**
   * Grants permission to create a new Amazon FSx file system from an existing backu
   * p
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystemFromBackup.html
   */
  CreateFileSystemFromBackup = 'fsx:CreateFileSystemFromBackup',
  /**
   * Grants permission to create a new snapshot on a volume
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateSnapshot.html
   */
  CreateSnapshot = 'fsx:CreateSnapshot',
  /**
   * Grants permission to create a new storage virtual machine in an Amazon FSx for
   * Ontap file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateStorageVirtualMachine.html
   */
  CreateStorageVirtualMachine = 'fsx:CreateStorageVirtualMachine',
  /**
   * Grants permission to create a new volume
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateVolume.html
   */
  CreateVolume = 'fsx:CreateVolume',
  /**
   * Grants permission to create a new volume from backup
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateVolumeFromBackup.html
   */
  CreateVolumeFromBackup = 'fsx:CreateVolumeFromBackup',
  /**
   * Grants permission to delete a backup, deleting its contents. After deletion, th
   * e backup no longer exists, and its data is no longer available
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteBackup.html
   */
  DeleteBackup = 'fsx:DeleteBackup',
  /**
   * Grants permission to delete a data repository association
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteDataRepositoryAssociation.html
   */
  DeleteDataRepositoryAssociation = 'fsx:DeleteDataRepositoryAssociation',
  /**
   * Grants permission to delete a file cache, deleting its contents
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteFileCache.html
   */
  DeleteFileCache = 'fsx:DeleteFileCache',
  /**
   * Grants permission to delete a file system, deleting its contents and any existi
   * ng automatic backups of the file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteFileSystem.html
   */
  DeleteFileSystem = 'fsx:DeleteFileSystem',
  /**
   * Required to manage cross-account sharing of FSx volumes through AWS Resource Ac
   * cess Manager (RAM). PutResourcePolicy and GetResourcePolicy are also required
   *
   * See https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/on-demand-replication.html
   */
  DeleteResourcePolicy = 'fsx:DeleteResourcePolicy',
  /**
   * Grants permission to delete a snapshot on a volume
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteSnapshot.html
   */
  DeleteSnapshot = 'fsx:DeleteSnapshot',
  /**
   * Grants permission to delete a storage virtual machine, deleting its contents
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteStorageVirtualMachine.html
   */
  DeleteStorageVirtualMachine = 'fsx:DeleteStorageVirtualMachine',
  /**
   * Grants permission to delete a volume, deleting its contents and any existing au
   * tomatic backups of the volume
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteVolume.html
   */
  DeleteVolume = 'fsx:DeleteVolume',
  /**
   * Grants permission to describe the File Gateway instances associated with an Ama
   * zon FSx for Windows File Server file system
   *
   * See https://docs.aws.amazon.com/filegateway/latest/filefsxw/what-is-file-fsxw.html
   */
  DescribeAssociatedFileGateways = 'fsx:DescribeAssociatedFileGateways',
  /**
   * Grants permission to return the descriptions of all backups owned by your AWS a
   * ccount in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeBackups.html
   */
  DescribeBackups = 'fsx:DescribeBackups',
  /**
   * Grants permission to return the descriptions of all data repository association
   * s owned by your AWS account in the AWS Region of the endpoint that you're calli
   * ng
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeDataRepositoryAssociations.html
   */
  DescribeDataRepositoryAssociations = 'fsx:DescribeDataRepositoryAssociations',
  /**
   * Grants permission to return the descriptions of all data repository tasks owned
   * by your AWS account in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeDataRepositoryTasks.html
   */
  DescribeDataRepositoryTasks = 'fsx:DescribeDataRepositoryTasks',
  /**
   * Grants permission to return the descriptions of all file caches owned by your A
   * WS account in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeFileCaches.html
   */
  DescribeFileCaches = 'fsx:DescribeFileCaches',
  /**
   * Grants permission to return the description of all DNS aliases owned by your Am
   * azon FSx for Windows File Server file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeFileSystemAliases.html
   */
  DescribeFileSystemAliases = 'fsx:DescribeFileSystemAliases',
  /**
   * Grants permission to return the descriptions of all file systems owned by your
   * AWS account in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeFileSystems.html
   */
  DescribeFileSystems = 'fsx:DescribeFileSystems',
  /**
   * Grants permission to return the descriptions of whether FSx route table updates
   * from participant accounts are allowed in your account
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeSharedVpcConfiguration.html
   */
  DescribeSharedVpcConfiguration = 'fsx:DescribeSharedVpcConfiguration',
  /**
   * Grants permission to return the descriptions of all snapshots owned by your AWS
   * account in the AWS Region of the endpoint you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeSnapshots.html
   */
  DescribeSnapshots = 'fsx:DescribeSnapshots',
  /**
   * Grants permission to return the descriptions of all storage virtual machines ow
   * ned by your AWS account in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeStorageVirtualMachines.html
   */
  DescribeStorageVirtualMachines = 'fsx:DescribeStorageVirtualMachines',
  /**
   * Grants permission to return the descriptions of all volumes owned by your AWS a
   * ccount in the AWS Region of the endpoint that you're calling
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeVolumes.html
   */
  DescribeVolumes = 'fsx:DescribeVolumes',
  /**
   * Grants permission to disassociate a File Gateway instance from an Amazon FSx fo
   * r Windows File Server file system
   *
   * See https://docs.aws.amazon.com/filegateway/latest/filefsxw/what-is-file-fsxw.html
   */
  DisassociateFileGateway = 'fsx:DisassociateFileGateway',
  /**
   * Grants permission to disassociate file system aliases with an Amazon FSx for Wi
   * ndows File Server file system
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_DisassociateFileSystemAliases.html
   */
  DisassociateFileSystemAliases = 'fsx:DisassociateFileSystemAliases',
  /**
   * Required to manage cross-account sharing of FSx volumes through AWS Resource Ac
   * cess Manager (RAM). PutResourcePolicy and DeleteResourcePolicy are also require
   * d
   *
   * See https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/on-demand-replication.html
   */
  GetResourcePolicy = 'fsx:GetResourcePolicy',
  /**
   * Grants permission to list tags for an Amazon FSx resource
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'fsx:ListTagsForResource',
  /**
   * Grants permission to manage backup principal associations through AWS Backup
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_CopyBackup.html
   */
  ManageBackupPrincipalAssociations = 'fsx:ManageBackupPrincipalAssociations',
  /**
   * Required to manage cross-account sharing of FSx volumes through AWS Resource Ac
   * cess Manager (RAM). DeleteResourcePolicy and GetResourcePolicy are also require
   * d
   *
   * See https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/on-demand-replication.html
   */
  PutResourcePolicy = 'fsx:PutResourcePolicy',
  /**
   * Grants permission to release file system NFS V3 locks
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_ReleaseFileSystemNfsV3Locks.html
   */
  ReleaseFileSystemNfsV3Locks = 'fsx:ReleaseFileSystemNfsV3Locks',
  /**
   * Grants permission to restore volume state from a snapshot
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_RestoreVolumeFromSnapshot.html
   */
  RestoreVolumeFromSnapshot = 'fsx:RestoreVolumeFromSnapshot',
  /**
   * Grants permission to start misconfigured state recovery
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_StartMisconfiguredStateRecovery.html
   */
  StartMisconfiguredStateRecovery = 'fsx:StartMisconfiguredStateRecovery',
  /**
   * Grants permission to tag an Amazon FSx resource
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_TagResource.html
   */
  TagResource = 'fsx:TagResource',
  /**
   * Grants permission to remove a tag from an Amazon FSx resource
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'fsx:UntagResource',
  /**
   * Grants permission to update data repository association configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateDataRepositoryAssociation.html
   */
  UpdateDataRepositoryAssociation = 'fsx:UpdateDataRepositoryAssociation',
  /**
   * Grants permission to update file cache configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateFileCache.html
   */
  UpdateFileCache = 'fsx:UpdateFileCache',
  /**
   * Grants permission to update file system configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateFileSystem.html
   */
  UpdateFileSystem = 'fsx:UpdateFileSystem',
  /**
   * Grants permission to enable or disable FSx route table updates from participant
   * accounts in your account
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateSharedVpcConfiguration.html
   */
  UpdateSharedVpcConfiguration = 'fsx:UpdateSharedVpcConfiguration',
  /**
   * Grants permission to update snapshot configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateSnapshot.html
   */
  UpdateSnapshot = 'fsx:UpdateSnapshot',
  /**
   * Grants permission to update storage virtual machine configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateStorageVirtualMachine.html
   */
  UpdateStorageVirtualMachine = 'fsx:UpdateStorageVirtualMachine',
  /**
   * Grants permission to update volume configuration
   *
   * See https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateVolume.html
   */
  UpdateVolume = 'fsx:UpdateVolume',
}
