// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Honeycode (HONEYCODE)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonhoneycode.html
 *
 * 2024-02-12T09:57:36.602Z
 */
export enum AwsHoneycodeActions {
  /**
   * Grants permission to approve a team association request for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team-association.html#approve-team-association
   */
  ApproveTeamAssociation = 'honeycode:ApproveTeamAssociation',
  /**
   * Grants permission to create new rows in a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_BatchCreateTableRows.html
   */
  BatchCreateTableRows = 'honeycode:BatchCreateTableRows',
  /**
   * Grants permission to delete rows from a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_BatchDeleteTableRows.html
   */
  BatchDeleteTableRows = 'honeycode:BatchDeleteTableRows',
  /**
   * Grants permission to update rows in a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_BatchUpdateTableRows.html
   */
  BatchUpdateTableRows = 'honeycode:BatchUpdateTableRows',
  /**
   * Grants permission to upsert rows in a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_BatchUpsertTableRows.html
   */
  BatchUpsertTableRows = 'honeycode:BatchUpsertTableRows',
  /**
   * Grants permission to create a new Amazon Honeycode team for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team.html#create-team
   */
  CreateTeam = 'honeycode:CreateTeam',
  /**
   * Grants permission to create a new tenant within Amazon Honeycode for your AWS A
   * ccount
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/tenant.html#create-tenant
   */
  CreateTenant = 'honeycode:CreateTenant',
  /**
   * Grants permission to delete Amazon Honeycode domains for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/domain.html#delete-domains
   */
  DeleteDomains = 'honeycode:DeleteDomains',
  /**
   * Grants permission to remove groups from an Amazon Honeycode team for your AWS A
   * ccount
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/group.html#deregister-groups
   */
  DeregisterGroups = 'honeycode:DeregisterGroups',
  /**
   * Grants permission to get details about a table data import job
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_DescribeTableDataImportJob.html
   */
  DescribeTableDataImportJob = 'honeycode:DescribeTableDataImportJob',
  /**
   * Grants permission to get details about Amazon Honeycode teams for your AWS Acco
   * unt
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team.html#describe-team
   */
  DescribeTeam = 'honeycode:DescribeTeam',
  /**
   * Grants permission to load the data from a screen
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_GetScreenData.html
   */
  GetScreenData = 'honeycode:GetScreenData',
  /**
   * Grants permission to invoke a screen automation
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_InvokeScreenAutomation.html
   */
  InvokeScreenAutomation = 'honeycode:InvokeScreenAutomation',
  /**
   * Grants permission to list all Amazon Honeycode domains and their verification s
   * tatus for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/domain.html#list-domains
   */
  ListDomains = 'honeycode:ListDomains',
  /**
   * Grants permission to list all groups in an Amazon Honeycode team for your AWS A
   * ccount
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/group.html#list-groups
   */
  ListGroups = 'honeycode:ListGroups',
  /**
   * Grants permission to list the columns in a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_ListTableColumns.html
   */
  ListTableColumns = 'honeycode:ListTableColumns',
  /**
   * Grants permission to list the rows in a table
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_ListTableRows.html
   */
  ListTableRows = 'honeycode:ListTableRows',
  /**
   * Grants permission to list the tables in a workbook
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_ListTables.html
   */
  ListTables = 'honeycode:ListTables',
  /**
   * Grants permission to list all tags for a resource
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_ListTagsForResource.html
   */
  ListTagsForResource = 'honeycode:ListTagsForResource',
  /**
   * Grants permission to list all pending and approved team associations with your
   * AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team-association.html#list-team-associations
   */
  ListTeamAssociations = 'honeycode:ListTeamAssociations',
  /**
   * Grants permission to list all tenants of Amazon Honeycode for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/tenant.html#list-tenants
   */
  ListTenants = 'honeycode:ListTenants',
  /**
   * Grants permission to query the rows of a table using a filter
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_QueryTableRows.html
   */
  QueryTableRows = 'honeycode:QueryTableRows',
  /**
   * Grants permission to request verification of the Amazon Honeycode domains for y
   * our AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/domain.html#register-domain-for-verification
   */
  RegisterDomainForVerification = 'honeycode:RegisterDomainForVerification',
  /**
   * Grants permission to add groups to an Amazon Honeycode team for your AWS Accoun
   * t
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/group.html#register-groups
   */
  RegisterGroups = 'honeycode:RegisterGroups',
  /**
   * Grants permission to reject a team association request for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team-association.html#reject-team-association
   */
  RejectTeamAssociation = 'honeycode:RejectTeamAssociation',
  /**
   * Grants permission to restart verification of the Amazon Honeycode domains for y
   * our AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/domain.html#restart-domain-verification
   */
  RestartDomainVerification = 'honeycode:RestartDomainVerification',
  /**
   * Grants permission to start a table data import job
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_StartTableDataImportJob.html
   */
  StartTableDataImportJob = 'honeycode:StartTableDataImportJob',
  /**
   * Grants permission to tag a resource
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_TagResource.html
   */
  TagResource = 'honeycode:TagResource',
  /**
   * Grants permission to untag a resource
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/API_UntagResource.html
   */
  UntagResource = 'honeycode:UntagResource',
  /**
   * Grants permission to update an Amazon Honeycode team for your AWS Account
   *
   * See https://docs.aws.amazon.com/honeycode/latest/UserGuide/team.html#update-team
   */
  UpdateTeam = 'honeycode:UpdateTeam',
}
