// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Identity Store (IDENTITYSTORE)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsidentitystore.html
 *
 * 2025-02-24T21:48:16.490Z
 */
export enum AwsIdentitystoreActions {
  /**
   * Grants permission to create a group in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_CreateGroup.html
   */
  CreateGroup = 'identitystore:CreateGroup',
  /**
   * Grants permission to create a member to a group in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_CreateGroupMembership.html
   */
  CreateGroupMembership = 'identitystore:CreateGroupMembership',
  /**
   * Grants permission to create a user in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_CreateUser.html
   */
  CreateUser = 'identitystore:CreateUser',
  /**
   * Grants permission to delete a group in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DeleteGroup.html
   */
  DeleteGroup = 'identitystore:DeleteGroup',
  /**
   * Grants permission to remove a member that is part of a group in the specified I
   * dentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DeleteGroupMembership.html
   */
  DeleteGroupMembership = 'identitystore:DeleteGroupMembership',
  /**
   * Grants permission to delete a user in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DeleteUser.html
   */
  DeleteUser = 'identitystore:DeleteUser',
  /**
   * Grants permission to retrieve information about a group in the specified Identi
   * tyStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DescribeGroup.html
   */
  DescribeGroup = 'identitystore:DescribeGroup',
  /**
   * Grants permission to retrieve information about a member that is part of a grou
   * p in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DescribeGroupMembership.html
   */
  DescribeGroupMembership = 'identitystore:DescribeGroupMembership',
  /**
   * Grants permission to retrieve information about user in the specified IdentityS
   * tore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DescribeUser.html
   */
  DescribeUser = 'identitystore:DescribeUser',
  /**
   * Grants permission to retrieve ID information about group in the specified Ident
   * ityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetGroupId.html
   */
  GetGroupId = 'identitystore:GetGroupId',
  /**
   * Grants permission to retrieve ID information of a member which is part of a gro
   * up in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetGroupMembershipId.html
   */
  GetGroupMembershipId = 'identitystore:GetGroupMembershipId',
  /**
   * Grants permission to retrieves ID information about user in the specified Ident
   * ityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetUserId.html
   */
  GetUserId = 'identitystore:GetUserId',
  /**
   * Grants permission to check if a member is a part of groups in the specified Ide
   * ntityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_IsMemberInGroups.html
   */
  IsMemberInGroups = 'identitystore:IsMemberInGroups',
  /**
   * Grants permission to retrieve all members that are part of a group in the speci
   * fied IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroupMemberships.html
   */
  ListGroupMemberships = 'identitystore:ListGroupMemberships',
  /**
   * Grants permission to list groups of the target member in the specified Identity
   * Store
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroupMembershipsForMember.html
   */
  ListGroupMembershipsForMember = 'identitystore:ListGroupMembershipsForMember',
  /**
   * Grants permission to search for groups within the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroups.html
   */
  ListGroups = 'identitystore:ListGroups',
  /**
   * Grants permission to search for users in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html
   */
  ListUsers = 'identitystore:ListUsers',
  /**
   * Grants permission to update information about a group in the specified Identity
   * Store
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateGroup.html
   */
  UpdateGroup = 'identitystore:UpdateGroup',
  /**
   * Grants permission to update user information in the specified IdentityStore
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateUser.html
   */
  UpdateUser = 'identitystore:UpdateUser',
}
