// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Marketplace Commerce Analytics Service (MARKETPLACECOMMERCEANALYTICS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsmarketplacecommerceanalyticsservice.html
 *
 * 2024-02-12T09:58:15.822Z
 */
export enum AwsMarketplacecommerceanalyticsActions {
  
}
