// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Application Migration Service (MGN)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsapplicationmigrationservice.html
 *
 * 2024-02-12T09:56:04.306Z
 */
export enum AwsMgnActions {
  /**
   * Grants permission to archive an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ArchiveApplication.html
   */
  ArchiveApplication = 'mgn:ArchiveApplication',
  /**
   * Grants permission to archive a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ArchiveWave.html
   */
  ArchiveWave = 'mgn:ArchiveWave',
  /**
   * Grants permission to associate applications to a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_AssociateApplications.html
   */
  AssociateApplications = 'mgn:AssociateApplications',
  /**
   * Grants permission to associate source servers to an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_AssociateSourceServers.html
   */
  AssociateSourceServers = 'mgn:AssociateSourceServers',
  /**
   * Grants permission to create volume snapshot group
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  BatchCreateVolumeSnapshotGroupForMgn = 'mgn:BatchCreateVolumeSnapshotGroupForMgn',
  /**
   * Grants permission to batch delete snapshot request
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  BatchDeleteSnapshotRequestForMgn = 'mgn:BatchDeleteSnapshotRequestForMgn',
  /**
   * Grants permission to change source server life cycle state
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ChangeServerLifeCycleState.html
   */
  ChangeServerLifeCycleState = 'mgn:ChangeServerLifeCycleState',
  /**
   * Grants permission to create an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_CreateApplication.html
   */
  CreateApplication = 'mgn:CreateApplication',
  /**
   * Grants permission to create connector
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_CreateConnector.html
   */
  CreateConnector = 'mgn:CreateConnector',
  /**
   * Grants permission to create launch configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_CreateLaunchConfigurationTemplate.html
   */
  CreateLaunchConfigurationTemplate = 'mgn:CreateLaunchConfigurationTemplate',
  /**
   * Grants permission to create replication configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_CreateReplicationConfigurationTemplate.html
   */
  CreateReplicationConfigurationTemplate = 'mgn:CreateReplicationConfigurationTemplate',
  /**
   * Grants permission to create vcenter client
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  CreateVcenterClientForMgn = 'mgn:CreateVcenterClientForMgn',
  /**
   * Grants permission to create a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_CreateWave.html
   */
  CreateWave = 'mgn:CreateWave',
  /**
   * Grants permission to delete an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteApplication.html
   */
  DeleteApplication = 'mgn:DeleteApplication',
  /**
   * Grants permission to delete connector
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteConnector.html
   */
  DeleteConnector = 'mgn:DeleteConnector',
  /**
   * Grants permission to delete job
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteJob.html
   */
  DeleteJob = 'mgn:DeleteJob',
  /**
   * Grants permission to delete launch configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteLaunchConfigurationTemplate.html
   */
  DeleteLaunchConfigurationTemplate = 'mgn:DeleteLaunchConfigurationTemplate',
  /**
   * Grants permission to delete replication configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteReplicationConfigurationTemplate.html
   */
  DeleteReplicationConfigurationTemplate = 'mgn:DeleteReplicationConfigurationTemplate',
  /**
   * Grants permission to delete source server
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteSourceServer.html
   */
  DeleteSourceServer = 'mgn:DeleteSourceServer',
  /**
   * Grants permission to delete vcenter client
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteVcenterClient.html
   */
  DeleteVcenterClient = 'mgn:DeleteVcenterClient',
  /**
   * Grants permission to delete a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DeleteWave.html
   */
  DeleteWave = 'mgn:DeleteWave',
  /**
   * Grants permission to describe job log items
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeJobLogItems.html
   */
  DescribeJobLogItems = 'mgn:DescribeJobLogItems',
  /**
   * Grants permission to describe jobs
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeJobs.html
   */
  DescribeJobs = 'mgn:DescribeJobs',
  /**
   * Grants permission to describe launch configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeLaunchConfigurationTemplates.html
   */
  DescribeLaunchConfigurationTemplates = 'mgn:DescribeLaunchConfigurationTemplates',
  /**
   * Grants permission to describe replication configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeReplicationConfigurationTemplates.html
   */
  DescribeReplicationConfigurationTemplates = 'mgn:DescribeReplicationConfigurationTemplates',
  /**
   * Grants permission to describe replication server associations
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  DescribeReplicationServerAssociationsForMgn = 'mgn:DescribeReplicationServerAssociationsForMgn',
  /**
   * Grants permission to describe snapshots requests
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  DescribeSnapshotRequestsForMgn = 'mgn:DescribeSnapshotRequestsForMgn',
  /**
   * Grants permission to describe source servers
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeSourceServers.html
   */
  DescribeSourceServers = 'mgn:DescribeSourceServers',
  /**
   * Grants permission to describe vcenter clients
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DescribeVcenterClients.html
   */
  DescribeVcenterClients = 'mgn:DescribeVcenterClients',
  /**
   * Grants permission to disassociate applications from a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DisassociateApplications.html
   */
  DisassociateApplications = 'mgn:DisassociateApplications',
  /**
   * Grants permission to disassociate source servers from an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DisassociateSourceServers.html
   */
  DisassociateSourceServers = 'mgn:DisassociateSourceServers',
  /**
   * Grants permission to disconnect source server from service
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_DisconnectFromService.html
   */
  DisconnectFromService = 'mgn:DisconnectFromService',
  /**
   * Grants permission to finalize cutover
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_FinalizeCutover.html
   */
  FinalizeCutover = 'mgn:FinalizeCutover',
  /**
   * Grants permission to get agent command
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentCommandForMgn = 'mgn:GetAgentCommandForMgn',
  /**
   * Grants permission to get agent confirmed resume info
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentConfirmedResumeInfoForMgn = 'mgn:GetAgentConfirmedResumeInfoForMgn',
  /**
   * Grants permission to get agent installation assets
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentInstallationAssetsForMgn = 'mgn:GetAgentInstallationAssetsForMgn',
  /**
   * Grants permission to get agent replication info
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentReplicationInfoForMgn = 'mgn:GetAgentReplicationInfoForMgn',
  /**
   * Grants permission to get agent runtime configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentRuntimeConfigurationForMgn = 'mgn:GetAgentRuntimeConfigurationForMgn',
  /**
   * Grants permission to get agent snapshots credits
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetAgentSnapshotCreditsForMgn = 'mgn:GetAgentSnapshotCreditsForMgn',
  /**
   * Grants permission to get channel commands
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetChannelCommandsForMgn = 'mgn:GetChannelCommandsForMgn',
  /**
   * Grants permission to get launch configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_GetLaunchConfiguration.html
   */
  GetLaunchConfiguration = 'mgn:GetLaunchConfiguration',
  /**
   * Grants permission to get replication configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_GetReplicationConfiguration.html
   */
  GetReplicationConfiguration = 'mgn:GetReplicationConfiguration',
  /**
   * Grants permission to get vcenter client commands
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  GetVcenterClientCommandsForMgn = 'mgn:GetVcenterClientCommandsForMgn',
  /**
   * Grants permission to initialize service
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_InitializeService.html
   */
  InitializeService = 'mgn:InitializeService',
  /**
   * Grants permission to issue a client certificate
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  IssueClientCertificateForMgn = 'mgn:IssueClientCertificateForMgn',
  /**
   * Grants permission to list application summaries
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListApplications.html
   */
  ListApplications = 'mgn:ListApplications',
  /**
   * Grants permission to list connectors
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListConnectors.html
   */
  ListConnectors = 'mgn:ListConnectors',
  /**
   * Grants permission to list the errors of an export task
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListExportErrors.html
   */
  ListExportErrors = 'mgn:ListExportErrors',
  /**
   * Grants permission to list export tasks
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListExports.html
   */
  ListExports = 'mgn:ListExports',
  /**
   * Grants permission to list the errors of an import task
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListImportErrors.html
   */
  ListImportErrors = 'mgn:ListImportErrors',
  /**
   * Grants permission to list the import tasks
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListImports.html
   */
  ListImports = 'mgn:ListImports',
  /**
   * Grants permission to list managed accounts
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListManagedAccounts.html
   */
  ListManagedAccounts = 'mgn:ListManagedAccounts',
  /**
   * Grants permission to list source server action documents
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListSourceServerActions.html
   */
  ListSourceServerActions = 'mgn:ListSourceServerActions',
  /**
   * Grants permission to list tags for a resource
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'mgn:ListTagsForResource',
  /**
   * Grants permission to list launch configuration template action documents
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListTemplateActions.html
   */
  ListTemplateActions = 'mgn:ListTemplateActions',
  /**
   * Grants permission to list wave summaries
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ListWaves.html
   */
  ListWaves = 'mgn:ListWaves',
  /**
   * Grants permission to mark source server as archived
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_MarkAsArchived.html
   */
  MarkAsArchived = 'mgn:MarkAsArchived',
  /**
   * Grants permission to notify agent authentication
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  NotifyAgentAuthenticationForMgn = 'mgn:NotifyAgentAuthenticationForMgn',
  /**
   * Grants permission to notify agent is connected
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  NotifyAgentConnectedForMgn = 'mgn:NotifyAgentConnectedForMgn',
  /**
   * Grants permission to notify agent is disconnected
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  NotifyAgentDisconnectedForMgn = 'mgn:NotifyAgentDisconnectedForMgn',
  /**
   * Grants permission to notify agent replication progress
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  NotifyAgentReplicationProgressForMgn = 'mgn:NotifyAgentReplicationProgressForMgn',
  /**
   * Grants permission to notify vcenter client started
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  NotifyVcenterClientStartedForMgn = 'mgn:NotifyVcenterClientStartedForMgn',
  /**
   * Grants permission to pause replication
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_PauseReplication.html
   */
  PauseReplication = 'mgn:PauseReplication',
  /**
   * Grants permission to put source server action document
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_PutSourceServerAction.html
   */
  PutSourceServerAction = 'mgn:PutSourceServerAction',
  /**
   * Grants permission to put launch configuration template action document
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_PutTemplateAction.html
   */
  PutTemplateAction = 'mgn:PutTemplateAction',
  /**
   * Grants permission to register agent
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  RegisterAgentForMgn = 'mgn:RegisterAgentForMgn',
  /**
   * Grants permission to remove source server action document
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_RemoveSourceServerAction.html
   */
  RemoveSourceServerAction = 'mgn:RemoveSourceServerAction',
  /**
   * Grants permission to remove launch configuration template action document
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_RemoveTemplateAction.html
   */
  RemoveTemplateAction = 'mgn:RemoveTemplateAction',
  /**
   * Grants permission to resume replication
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_ResumeReplication.html
   */
  ResumeReplication = 'mgn:ResumeReplication',
  /**
   * Grants permission to retry replication
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_RetryDataReplication.html
   */
  RetryDataReplication = 'mgn:RetryDataReplication',
  /**
   * Grants permission to send agent logs
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendAgentLogsForMgn = 'mgn:SendAgentLogsForMgn',
  /**
   * Grants permission to send agent metrics
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendAgentMetricsForMgn = 'mgn:SendAgentMetricsForMgn',
  /**
   * Grants permission to send channel command result
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendChannelCommandResultForMgn = 'mgn:SendChannelCommandResultForMgn',
  /**
   * Grants permission to send client logs
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendClientLogsForMgn = 'mgn:SendClientLogsForMgn',
  /**
   * Grants permission to send client metrics
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendClientMetricsForMgn = 'mgn:SendClientMetricsForMgn',
  /**
   * Grants permission to send vcenter client command result
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendVcenterClientCommandResultForMgn = 'mgn:SendVcenterClientCommandResultForMgn',
  /**
   * Grants permission to send vcenter client logs
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendVcenterClientLogsForMgn = 'mgn:SendVcenterClientLogsForMgn',
  /**
   * Grants permission to send vcenter client metrics
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  SendVcenterClientMetricsForMgn = 'mgn:SendVcenterClientMetricsForMgn',
  /**
   * Grants permission to start cutover
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StartCutover.html
   */
  StartCutover = 'mgn:StartCutover',
  /**
   * Grants permission to start an export task
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StartExport.html
   */
  StartExport = 'mgn:StartExport',
  /**
   * Grants permission to create an import task
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StartImport.html
   */
  StartImport = 'mgn:StartImport',
  /**
   * Grants permission to start replication
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StartReplication.html
   */
  StartReplication = 'mgn:StartReplication',
  /**
   * Grants permission to start test
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StartTest.html
   */
  StartTest = 'mgn:StartTest',
  /**
   * Grants permission to stop replication
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_StopReplication.html
   */
  StopReplication = 'mgn:StopReplication',
  /**
   * Grants permission to assign a resource tag
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_TagResource.html
   */
  TagResource = 'mgn:TagResource',
  /**
   * Grants permission to terminate target instances
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_TerminateTargetInstances.html
   */
  TerminateTargetInstances = 'mgn:TerminateTargetInstances',
  /**
   * Grants permission to unarchive an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UnarchiveApplication.html
   */
  UnarchiveApplication = 'mgn:UnarchiveApplication',
  /**
   * Grants permission to unarchive a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UnarchiveWave.html
   */
  UnarchiveWave = 'mgn:UnarchiveWave',
  /**
   * Grants permission to untag a resource
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'mgn:UntagResource',
  /**
   * Grants permission to update agent backlog
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  UpdateAgentBacklogForMgn = 'mgn:UpdateAgentBacklogForMgn',
  /**
   * Grants permission to update agent conversion info
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  UpdateAgentConversionInfoForMgn = 'mgn:UpdateAgentConversionInfoForMgn',
  /**
   * Grants permission to update agent replication info
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  UpdateAgentReplicationInfoForMgn = 'mgn:UpdateAgentReplicationInfoForMgn',
  /**
   * Grants permission to update agent replication process state
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  UpdateAgentReplicationProcessStateForMgn = 'mgn:UpdateAgentReplicationProcessStateForMgn',
  /**
   * Grants permission to update agent source properties
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  UpdateAgentSourcePropertiesForMgn = 'mgn:UpdateAgentSourcePropertiesForMgn',
  /**
   * Grants permission to update an application
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateApplication.html
   */
  UpdateApplication = 'mgn:UpdateApplication',
  /**
   * Grants permission to update connector
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateConnector.html
   */
  UpdateConnector = 'mgn:UpdateConnector',
  /**
   * Grants permission to update launch configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateLaunchConfiguration.html
   */
  UpdateLaunchConfiguration = 'mgn:UpdateLaunchConfiguration',
  /**
   * Grants permission to update launch configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateLaunchConfigurationTemplate.html
   */
  UpdateLaunchConfigurationTemplate = 'mgn:UpdateLaunchConfigurationTemplate',
  /**
   * Grants permission to update replication configuration
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateReplicationConfiguration.html
   */
  UpdateReplicationConfiguration = 'mgn:UpdateReplicationConfiguration',
  /**
   * Grants permission to update replication configuration template
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateReplicationConfigurationTemplate.html
   */
  UpdateReplicationConfigurationTemplate = 'mgn:UpdateReplicationConfigurationTemplate',
  /**
   * Grants permission to update source server
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateSourceServer.html
   */
  UpdateSourceServer = 'mgn:UpdateSourceServer',
  /**
   * Grants permission to update source server replication type
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateSourceServerReplicationType.html
   */
  UpdateSourceServerReplicationType = 'mgn:UpdateSourceServerReplicationType',
  /**
   * Grants permission to update a wave
   *
   * See https://docs.aws.amazon.com/mgn/latest/APIReference/API_UpdateWave.html
   */
  UpdateWave = 'mgn:UpdateWave',
  /**
   * Grants permission to verify client role
   *
   * See https://docs.aws.amazon.com/mgn/latest/ug/mgn-apis.html
   */
  VerifyClientRoleForMgn = 'mgn:VerifyClientRoleForMgn',
}
