// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS User Notifications Contacts (NOTIFICATIONS-CONTACTS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsusernotificationscontacts.html
 *
 * 2024-02-12T09:59:34.992Z
 */
export enum AwsNotificationsContactsActions {
  /**
   * Grants permission to activate the email contact associated with the given ARN i
   * f the provided code is valid
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  ActivateEmailContact = 'notifications-contacts:ActivateEmailContact',
  /**
   * Grants permission to create an email contact
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  CreateEmailContact = 'notifications-contacts:CreateEmailContact',
  /**
   * Grants permission to delete an email contact associated with the given ARN
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  DeleteEmailContact = 'notifications-contacts:DeleteEmailContact',
  /**
   * Grants permission to get an email contact associated with the given ARN
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  GetEmailContact = 'notifications-contacts:GetEmailContact',
  /**
   * Grants permission to list email contacts
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  ListEmailContacts = 'notifications-contacts:ListEmailContacts',
  /**
   * Grants permission to get tags for a resource
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  ListTagsForResource = 'notifications-contacts:ListTagsForResource',
  /**
   * Grants permission to send an activation link to the email associated with the g
   * iven ARN
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  SendActivationCode = 'notifications-contacts:SendActivationCode',
  /**
   * Grants permission to tag a resource
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  TagResource = 'notifications-contacts:TagResource',
  /**
   * Grants permission to remove tags from a resource
   *
   * See https://docs.aws.amazon.com/notifications/latest/userguide/resource-level-permissions.html
   */
  UntagResource = 'notifications-contacts:UntagResource',
}
