// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Proton (PROTON)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsproton.html
 *
 * 2024-02-12T09:58:44.421Z
 */
export enum AwsProtonActions {
  /**
   * Grants permission to reject an environment account connection request from anot
   * her environment account
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_AcceptEnvironmentAccountConnection.html
   */
  AcceptEnvironmentAccountConnection = 'proton:AcceptEnvironmentAccountConnection',
  /**
   * Grants permission to cancel component deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CancelComponentDeployment.html
   */
  CancelComponentDeployment = 'proton:CancelComponentDeployment',
  /**
   * Grants permission to cancel an environment deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CancelEnvironmentDeployment.html
   */
  CancelEnvironmentDeployment = 'proton:CancelEnvironmentDeployment',
  /**
   * Grants permission to cancel a service instance deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CancelServiceInstanceDeployment.html
   */
  CancelServiceInstanceDeployment = 'proton:CancelServiceInstanceDeployment',
  /**
   * Grants permission to cancel a service pipeline deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CancelServicePipelineDeployment.html
   */
  CancelServicePipelineDeployment = 'proton:CancelServicePipelineDeployment',
  /**
   * Grants permission to create component
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateComponent.html
   */
  CreateComponent = 'proton:CreateComponent',
  /**
   * Grants permission to create an environment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironment.html
   */
  CreateEnvironment = 'proton:CreateEnvironment',
  /**
   * Grants permission to create an environment account connection
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironmentAccountConnection.html
   */
  CreateEnvironmentAccountConnection = 'proton:CreateEnvironmentAccountConnection',
  /**
   * Grants permission to create an environment template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironmentTemplate.html
   */
  CreateEnvironmentTemplate = 'proton:CreateEnvironmentTemplate',
  /**
   * Grants permission to create an environment template major version.  DEPRECATED
   * - use CreateEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironmentTemplateMajorVersion.html
   */
  CreateEnvironmentTemplateMajorVersion = 'proton:CreateEnvironmentTemplateMajorVersion',
  /**
   * Grants permission to create an environment template minor version.  DEPRECATED
   * - use CreateEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironmentTemplateMinorVersion.html
   */
  CreateEnvironmentTemplateMinorVersion = 'proton:CreateEnvironmentTemplateMinorVersion',
  /**
   * Grants permission to create an environment template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateEnvironmentTemplateVersion.html
   */
  CreateEnvironmentTemplateVersion = 'proton:CreateEnvironmentTemplateVersion',
  /**
   * Grants permission to create a repository
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateRepository.html
   */
  CreateRepository = 'proton:CreateRepository',
  /**
   * Grants permission to create a service
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateService.html
   */
  CreateService = 'proton:CreateService',
  /**
   * Grants permission to create a service instance
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceInstance.html
   */
  CreateServiceInstance = 'proton:CreateServiceInstance',
  /**
   * Grants permission to create a service sync config
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceSyncConfig.html
   */
  CreateServiceSyncConfig = 'proton:CreateServiceSyncConfig',
  /**
   * Grants permission to create a service template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceTemplate.html
   */
  CreateServiceTemplate = 'proton:CreateServiceTemplate',
  /**
   * Grants permission to create a service template major version.  DEPRECATED - use
   * CreateServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceTemplateMajorVersion.html
   */
  CreateServiceTemplateMajorVersion = 'proton:CreateServiceTemplateMajorVersion',
  /**
   * Grants permission to create a service template minor version.  DEPRECATED - use
   * CreateServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceTemplateMinorVersion.html
   */
  CreateServiceTemplateMinorVersion = 'proton:CreateServiceTemplateMinorVersion',
  /**
   * Grants permission to create a service template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateServiceTemplateVersion.html
   */
  CreateServiceTemplateVersion = 'proton:CreateServiceTemplateVersion',
  /**
   * Grants permission to create a template sync config
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_CreateTemplateSyncConfig.html
   */
  CreateTemplateSyncConfig = 'proton:CreateTemplateSyncConfig',
  /**
   * Grants permission to delete account roles.  DEPRECATED - use UpdateAccountSetti
   * ngs instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteAccountRoles.html
   */
  DeleteAccountRoles = 'proton:DeleteAccountRoles',
  /**
   * Grants permission to delete component
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteComponent.html
   */
  DeleteComponent = 'proton:DeleteComponent',
  /**
   * Grants permission to delete a deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteDeployment.html
   */
  DeleteDeployment = 'proton:DeleteDeployment',
  /**
   * Grants permission to delete an environment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironment.html
   */
  DeleteEnvironment = 'proton:DeleteEnvironment',
  /**
   * Grants permission to delete an environment account connection
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironmentAccountConnection.html
   */
  DeleteEnvironmentAccountConnection = 'proton:DeleteEnvironmentAccountConnection',
  /**
   * Grants permission to delete an environment template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironmentTemplate.html
   */
  DeleteEnvironmentTemplate = 'proton:DeleteEnvironmentTemplate',
  /**
   * Grants permission to delete an environment template major version.  DEPRECATED
   * - use DeleteEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironmentTemplateMajorVersion.html
   */
  DeleteEnvironmentTemplateMajorVersion = 'proton:DeleteEnvironmentTemplateMajorVersion',
  /**
   * Grants permission to delete an environment template minor version.  DEPRECATED
   * - use DeleteEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironmentTemplateMinorVersion.html
   */
  DeleteEnvironmentTemplateMinorVersion = 'proton:DeleteEnvironmentTemplateMinorVersion',
  /**
   * Grants permission to delete an environment template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteEnvironmentTemplateVersion.html
   */
  DeleteEnvironmentTemplateVersion = 'proton:DeleteEnvironmentTemplateVersion',
  /**
   * Grants permission to delete a repository
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteRepository.html
   */
  DeleteRepository = 'proton:DeleteRepository',
  /**
   * Grants permission to delete a service
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteService.html
   */
  DeleteService = 'proton:DeleteService',
  /**
   * Grants permission to delete a service sync config
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteServiceSyncConfig.html
   */
  DeleteServiceSyncConfig = 'proton:DeleteServiceSyncConfig',
  /**
   * Grants permission to delete a service template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteServiceTemplate.html
   */
  DeleteServiceTemplate = 'proton:DeleteServiceTemplate',
  /**
   * Grants permission to delete a service template major version.  DEPRECATED - use
   * DeleteServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteServiceTemplateMajorVersion.html
   */
  DeleteServiceTemplateMajorVersion = 'proton:DeleteServiceTemplateMajorVersion',
  /**
   * Grants permission to delete a service template minor version.  DEPRECATED - use
   * DeleteServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteServiceTemplateMinorVersion.html
   */
  DeleteServiceTemplateMinorVersion = 'proton:DeleteServiceTemplateMinorVersion',
  /**
   * Grants permission to delete a service template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteServiceTemplateVersion.html
   */
  DeleteServiceTemplateVersion = 'proton:DeleteServiceTemplateVersion',
  /**
   * Grants permission to delete a TemplateSyncConfig
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_DeleteTemplateSyncConfig.html
   */
  DeleteTemplateSyncConfig = 'proton:DeleteTemplateSyncConfig',
  /**
   * Grants permission to get account roles.  DEPRECATED - use GetAccountSettings in
   * stead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetAccountRoles.html
   */
  GetAccountRoles = 'proton:GetAccountRoles',
  /**
   * Grants permission to describe the account settings
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetAccountSettings.html
   */
  GetAccountSettings = 'proton:GetAccountSettings',
  /**
   * Grants permission to describe a component
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetComponent.html
   */
  GetComponent = 'proton:GetComponent',
  /**
   * Grants permission to describe a deployment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetDeployment.html
   */
  GetDeployment = 'proton:GetDeployment',
  /**
   * Grants permission to describe an environment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironment.html
   */
  GetEnvironment = 'proton:GetEnvironment',
  /**
   * Grants permission to describe an environment account connection
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironmentAccountConnection.html
   */
  GetEnvironmentAccountConnection = 'proton:GetEnvironmentAccountConnection',
  /**
   * Grants permission to describe an environment template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironmentTemplate.html
   */
  GetEnvironmentTemplate = 'proton:GetEnvironmentTemplate',
  /**
   * Grants permission to get an environment template major version.  DEPRECATED - u
   * se GetEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironmentTemplateMajorVersion.html
   */
  GetEnvironmentTemplateMajorVersion = 'proton:GetEnvironmentTemplateMajorVersion',
  /**
   * Grants permission to get an environment template minor version.  DEPRECATED - u
   * se GetEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironmentTemplateMinorVersion.html
   */
  GetEnvironmentTemplateMinorVersion = 'proton:GetEnvironmentTemplateMinorVersion',
  /**
   * Grants permission to describe an environment template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetEnvironmentTemplateVersion.html
   */
  GetEnvironmentTemplateVersion = 'proton:GetEnvironmentTemplateVersion',
  /**
   * Grants permission to describe a repository
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetRepository.html
   */
  GetRepository = 'proton:GetRepository',
  /**
   * Grants permission to get the latest sync status for a repository
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetRepositorySyncStatus.html
   */
  GetRepositorySyncStatus = 'proton:GetRepositorySyncStatus',
  /**
   * Grants permission to list resource template version status counts
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetResourceTemplateVersionStatusCounts.html
   */
  GetResourceTemplateVersionStatusCounts = 'proton:GetResourceTemplateVersionStatusCounts',
  /**
   * Grants permission to get resources summary
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetResourcesSummary.html
   */
  GetResourcesSummary = 'proton:GetResourcesSummary',
  /**
   * Grants permission to describe a service
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetService.html
   */
  GetService = 'proton:GetService',
  /**
   * Grants permission to describe a service instance
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceInstance.html
   */
  GetServiceInstance = 'proton:GetServiceInstance',
  /**
   * Grants permission to describe the sync status of a service instance
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceInstanceSyncStatus.html
   */
  GetServiceInstanceSyncStatus = 'proton:GetServiceInstanceSyncStatus',
  /**
   * Grants permission to describe service sync blockers on a service or service ins
   * tance
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceSyncBlockerSummary.html
   */
  GetServiceSyncBlockerSummary = 'proton:GetServiceSyncBlockerSummary',
  /**
   * Grants permission to describe a service sync config
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceSyncConfig.html
   */
  GetServiceSyncConfig = 'proton:GetServiceSyncConfig',
  /**
   * Grants permission to describe a service template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceTemplate.html
   */
  GetServiceTemplate = 'proton:GetServiceTemplate',
  /**
   * Grants permission to get a service template major version.  DEPRECATED - use Ge
   * tServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceTemplateMajorVersion.html
   */
  GetServiceTemplateMajorVersion = 'proton:GetServiceTemplateMajorVersion',
  /**
   * Grants permission to get a service template minor version.  DEPRECATED - use Ge
   * tServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceTemplateMinorVersion.html
   */
  GetServiceTemplateMinorVersion = 'proton:GetServiceTemplateMinorVersion',
  /**
   * Grants permission to describe a service template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetServiceTemplateVersion.html
   */
  GetServiceTemplateVersion = 'proton:GetServiceTemplateVersion',
  /**
   * Grants permission to describe a TemplateSyncConfig
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetTemplateSyncConfig.html
   */
  GetTemplateSyncConfig = 'proton:GetTemplateSyncConfig',
  /**
   * Grants permission to describe the sync status of a template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_GetTemplateSyncStatus.html
   */
  GetTemplateSyncStatus = 'proton:GetTemplateSyncStatus',
  /**
   * Grants permission to list component outputs
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListComponentOutputs.html
   */
  ListComponentOutputs = 'proton:ListComponentOutputs',
  /**
   * Grants permission to list component provisioned resources
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListComponentProvisionedResources.html
   */
  ListComponentProvisionedResources = 'proton:ListComponentProvisionedResources',
  /**
   * Grants permission to list components
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListComponents.html
   */
  ListComponents = 'proton:ListComponents',
  /**
   * Grants permission to list deployments
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListDeployments.html
   */
  ListDeployments = 'proton:ListDeployments',
  /**
   * Grants permission to list environment account connections
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentAccountConnections.html
   */
  ListEnvironmentAccountConnections = 'proton:ListEnvironmentAccountConnections',
  /**
   * Grants permission to list environment outputs
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentOutputs.html
   */
  ListEnvironmentOutputs = 'proton:ListEnvironmentOutputs',
  /**
   * Grants permission to list environment provisioned resources
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentProvisionedResources.html
   */
  ListEnvironmentProvisionedResources = 'proton:ListEnvironmentProvisionedResources',
  /**
   * Grants permission to list environment template major versions.  DEPRECATED - us
   * e ListEnvironmentTemplateVersions instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentTemplateMajorVersions.html
   */
  ListEnvironmentTemplateMajorVersions = 'proton:ListEnvironmentTemplateMajorVersions',
  /**
   * Grants permission to list an environment template minor versions.  DEPRECATED -
   * use ListEnvironmentTemplateVersions instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentTemplateMinorVersions.html
   */
  ListEnvironmentTemplateMinorVersions = 'proton:ListEnvironmentTemplateMinorVersions',
  /**
   * Grants permission to list environment template versions
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentTemplateVersions.html
   */
  ListEnvironmentTemplateVersions = 'proton:ListEnvironmentTemplateVersions',
  /**
   * Grants permission to list environment templates
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironmentTemplates.html
   */
  ListEnvironmentTemplates = 'proton:ListEnvironmentTemplates',
  /**
   * Grants permission to list environments
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListEnvironments.html
   */
  ListEnvironments = 'proton:ListEnvironments',
  /**
   * Grants permission to list repositories
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListRepositories.html
   */
  ListRepositories = 'proton:ListRepositories',
  /**
   * Grants permission to list repository sync definitions
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListRepositorySyncDefinitions.html
   */
  ListRepositorySyncDefinitions = 'proton:ListRepositorySyncDefinitions',
  /**
   * Grants permission to list service instance outputs
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceInstanceOutputs.html
   */
  ListServiceInstanceOutputs = 'proton:ListServiceInstanceOutputs',
  /**
   * Grants permission to list service instance provisioned resources
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceInstanceProvisionedResources.html
   */
  ListServiceInstanceProvisionedResources = 'proton:ListServiceInstanceProvisionedResources',
  /**
   * Grants permission to list service instances
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceInstances.html
   */
  ListServiceInstances = 'proton:ListServiceInstances',
  /**
   * Grants permission to list service pipeline outputs
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServicePipelineOutputs.html
   */
  ListServicePipelineOutputs = 'proton:ListServicePipelineOutputs',
  /**
   * Grants permission to list service pipeline provisioned resources
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServicePipelineProvisionedResources.html
   */
  ListServicePipelineProvisionedResources = 'proton:ListServicePipelineProvisionedResources',
  /**
   * Grants permission to list service template major versions.  DEPRECATED - use Li
   * stServiceTemplateVersions instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceTemplateMajorVersions.html
   */
  ListServiceTemplateMajorVersions = 'proton:ListServiceTemplateMajorVersions',
  /**
   * Grants permission to list service template minor versions.  DEPRECATED - use Li
   * stServiceTemplateVersions instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceTemplateMinorVersions.html
   */
  ListServiceTemplateMinorVersions = 'proton:ListServiceTemplateMinorVersions',
  /**
   * Grants permission to list service template versions
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceTemplateVersions.html
   */
  ListServiceTemplateVersions = 'proton:ListServiceTemplateVersions',
  /**
   * Grants permission to list service templates
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServiceTemplates.html
   */
  ListServiceTemplates = 'proton:ListServiceTemplates',
  /**
   * Grants permission to list services
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListServices.html
   */
  ListServices = 'proton:ListServices',
  /**
   * Grants permission to list tags of a resource
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'proton:ListTagsForResource',
  /**
   * Grants permission to notify Proton of resource deployment status changes
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_NotifyResourceDeploymentStatusChange.html
   */
  NotifyResourceDeploymentStatusChange = 'proton:NotifyResourceDeploymentStatusChange',
  /**
   * Grants permission to reject an environment account connection request from anot
   * her environment account
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_RejectEnvironmentAccountConnection.html
   */
  RejectEnvironmentAccountConnection = 'proton:RejectEnvironmentAccountConnection',
  /**
   * Grants permission to add tags to a resource
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_TagResource.html
   */
  TagResource = 'proton:TagResource',
  /**
   * Grants permission to remove tags from a resource
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'proton:UntagResource',
  /**
   * Grants permission to update account roles.  DEPRECATED - use UpdateAccountSetti
   * ngs instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateAccountRoles.html
   */
  UpdateAccountRoles = 'proton:UpdateAccountRoles',
  /**
   * Grants permission to update the account settings
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateAccountSettings.html
   */
  UpdateAccountSettings = 'proton:UpdateAccountSettings',
  /**
   * Grants permission to update component
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateComponent.html
   */
  UpdateComponent = 'proton:UpdateComponent',
  /**
   * Grants permission to update an environment
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironment.html
   */
  UpdateEnvironment = 'proton:UpdateEnvironment',
  /**
   * Grants permission to update an environment account connection
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironmentAccountConnection.html
   */
  UpdateEnvironmentAccountConnection = 'proton:UpdateEnvironmentAccountConnection',
  /**
   * Grants permission to update an environment template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironmentTemplate.html
   */
  UpdateEnvironmentTemplate = 'proton:UpdateEnvironmentTemplate',
  /**
   * Grants permission to update an environment template major version.  DEPRECATED
   * - use UpdateEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironmentTemplateMajorVersion.html
   */
  UpdateEnvironmentTemplateMajorVersion = 'proton:UpdateEnvironmentTemplateMajorVersion',
  /**
   * Grants permission to update an environment template minor version.  DEPRECATED
   * - use UpdateEnvironmentTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironmentTemplateMinorVersion.html
   */
  UpdateEnvironmentTemplateMinorVersion = 'proton:UpdateEnvironmentTemplateMinorVersion',
  /**
   * Grants permission to update an environment template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateEnvironmentTemplateVersion.html
   */
  UpdateEnvironmentTemplateVersion = 'proton:UpdateEnvironmentTemplateVersion',
  /**
   * Grants permission to update a service
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateService.html
   */
  UpdateService = 'proton:UpdateService',
  /**
   * Grants permission to update a service instance
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceInstance.html
   */
  UpdateServiceInstance = 'proton:UpdateServiceInstance',
  /**
   * Grants permission to update a service pipeline
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServicePipeline.html
   */
  UpdateServicePipeline = 'proton:UpdateServicePipeline',
  /**
   * Grants permission to update a service sync blocker
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceSyncBlocker.html
   */
  UpdateServiceSyncBlocker = 'proton:UpdateServiceSyncBlocker',
  /**
   * Grants permission to update a service sync config
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceSyncConfig.html
   */
  UpdateServiceSyncConfig = 'proton:UpdateServiceSyncConfig',
  /**
   * Grants permission to update a service template
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceTemplate.html
   */
  UpdateServiceTemplate = 'proton:UpdateServiceTemplate',
  /**
   * Grants permission to update a service template major version.  DEPRECATED - use
   * UpdateServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceTemplateMajorVersion.html
   */
  UpdateServiceTemplateMajorVersion = 'proton:UpdateServiceTemplateMajorVersion',
  /**
   * Grants permission to create a service template minor version.  DEPRECATED - use
   * UpdateServiceTemplateVersion instead
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceTemplateMinorVersion.html
   */
  UpdateServiceTemplateMinorVersion = 'proton:UpdateServiceTemplateMinorVersion',
  /**
   * Grants permission to update a service template version
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateServiceTemplateVersion.html
   */
  UpdateServiceTemplateVersion = 'proton:UpdateServiceTemplateVersion',
  /**
   * Grants permission to update a TemplateSyncConfig
   *
   * See https://docs.aws.amazon.com/proton/latest/APIReference/API_UpdateTemplateSyncConfig.html
   */
  UpdateTemplateSyncConfig = 'proton:UpdateTemplateSyncConfig',
}
