// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Q Business Q Apps (QAPPS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonqbusinessqapps.html
 *
 * 2025-02-24T21:49:18.756Z
 */
export enum AwsQappsActions {
  /**
   * Grants permission to associate a library item review in the Q Business applicat
   * ion environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_AssociateLibraryItemReview.html
   */
  AssociateLibraryItemReview = 'qapps:AssociateLibraryItemReview',
  /**
   * Grants permission to associate Q App with a user in the Q Business application
   * environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_AssociateQAppWithUser.html
   */
  AssociateQAppWithUser = 'qapps:AssociateQAppWithUser',
  /**
   * Grants permission to create the categories of a library in the Q Business appli
   * cation environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_BatchCreateCategory.html
   */
  BatchCreateCategory = 'qapps:BatchCreateCategory',
  /**
   * Grants permission to delete the categories of a library in the Q Business appli
   * cation environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_BatchDeleteCategory.html
   */
  BatchDeleteCategory = 'qapps:BatchDeleteCategory',
  /**
   * Grants permission to update the categories of a library in the Q Business appli
   * cation environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_BatchUpdateCategory.html
   */
  BatchUpdateCategory = 'qapps:BatchUpdateCategory',
  /**
   * Grants permission to copy Q App in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  CopyQApp = 'qapps:CopyQApp',
  /**
   * Grants permission to create a library item in the Q Business application enviro
   * nment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_CreateLibraryItem.html
   */
  CreateLibraryItem = 'qapps:CreateLibraryItem',
  /**
   * Grants permission to create a library item review in the Q Business application
   * environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  CreateLibraryItemReview = 'qapps:CreateLibraryItemReview',
  /**
   * Grants permission to create a presigned URL for uploading a file to a Q App or
   * Q App Session in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_CreatePresignedUrl.html
   */
  CreatePresignedUrl = 'qapps:CreatePresignedUrl',
  /**
   * Grants permission to create Q App in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_CreateQApp.html
   */
  CreateQApp = 'qapps:CreateQApp',
  /**
   * Grants permission to subscribe to a Q App event bus topic in the Q Business app
   * lication environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  CreateSubscriptionToken = 'qapps:CreateSubscriptionToken',
  /**
   * Grants permission to delete a library item in the Q Business application enviro
   * nment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_DeleteLibraryItem.html
   */
  DeleteLibraryItem = 'qapps:DeleteLibraryItem',
  /**
   * Grants permission to delete Q App in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_DeleteQApp.html
   */
  DeleteQApp = 'qapps:DeleteQApp',
  /**
   * Grants permission to get Q App sharing permissions in the Q Business applicatio
   * n environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_DescribeQAppPermissions.html
   */
  DescribeQAppPermissions = 'qapps:DescribeQAppPermissions',
  /**
   * Grants permission to disassociate a library item review in the Q Business appli
   * cation environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_DisassociateLibraryItemReview.html
   */
  DisassociateLibraryItemReview = 'qapps:DisassociateLibraryItemReview',
  /**
   * Grants permission to disassociate Q App with a user in the Q Business applicati
   * on environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_DisassociateQAppFromUser.html
   */
  DisassociateQAppFromUser = 'qapps:DisassociateQAppFromUser',
  /**
   * Grants permission to export Q App session data in the Q Business application en
   * vironment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  ExportQAppSessionData = 'qapps:ExportQAppSessionData',
  /**
   * Grants permission to get a library item in the Q Business application environme
   * nt
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_GetLibraryItem.html
   */
  GetLibraryItem = 'qapps:GetLibraryItem',
  /**
   * Grants permission to get Q App in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_GetQApp.html
   */
  GetQApp = 'qapps:GetQApp',
  /**
   * Grants permission to get Q App session in the Q Business application environmen
   * t
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_GetQAppSession.html
   */
  GetQAppSession = 'qapps:GetQAppSession',
  /**
   * Grants permission to get Q App session metadata in the Q Business application e
   * nvironment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  GetQAppSessionMetadata = 'qapps:GetQAppSessionMetadata',
  /**
   * Grants permission to import a document to Q App or Q App Session in the Q Busin
   * ess application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_ImportDocument.html
   */
  ImportDocument = 'qapps:ImportDocument',
  /**
   * Grants permission to import a document to Q App in the Q Business application e
   * nvironment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  ImportDocumentToQApp = 'qapps:ImportDocumentToQApp',
  /**
   * Grants permission to import a document to Q App session in the Q Business appli
   * cation environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  ImportDocumentToQAppSession = 'qapps:ImportDocumentToQAppSession',
  /**
   * Grants permission to list categories in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_ListCategories.html
   */
  ListCategories = 'qapps:ListCategories',
  /**
   * Grants permission to list library items in the Q Business application environme
   * nt
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_ListLibraryItems.html
   */
  ListLibraryItems = 'qapps:ListLibraryItems',
  /**
   * Grants permission to get Q App session data in the Q Business application envir
   * onment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  ListQAppSessionData = 'qapps:ListQAppSessionData',
  /**
   * Grants permission to list Q Apps in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_ListQApps.html
   */
  ListQApps = 'qapps:ListQApps',
  /**
   * Grants permission to list tags for a resource
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'qapps:ListTagsForResource',
  /**
   * Grants permission to predict problem statement from conversation log in the Q B
   * usiness application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  PredictProblemStatementFromConversation = 'qapps:PredictProblemStatementFromConversation',
  /**
   * Grants permission to predict Q App from conversation log or problem statement i
   * n the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_PredictQApp.html
   */
  PredictQApp = 'qapps:PredictQApp',
  /**
   * Grants permission to predict Q App metadata from problem statement in the Q Bus
   * iness application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  PredictQAppFromProblemStatement = 'qapps:PredictQAppFromProblemStatement',
  /**
   * Grants permission to start Q App session in the Q Business application environm
   * ent
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_StartQAppSession.html
   */
  StartQAppSession = 'qapps:StartQAppSession',
  /**
   * Grants permission to stop Q App session in the Q Business application environme
   * nt
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_StopQAppSession.html
   */
  StopQAppSession = 'qapps:StopQAppSession',
  /**
   * Grants permission to tag a resource with given key value pairs
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_TagResource.html
   */
  TagResource = 'qapps:TagResource',
  /**
   * Grants permission to remove the tag with the given key from a resource
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_UntagResource.html
   */
  UntagResource = 'qapps:UntagResource',
  /**
   * Grants permission to update a library item in the Q Business application enviro
   * nment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_UpdateLibraryItem.html
   */
  UpdateLibraryItem = 'qapps:UpdateLibraryItem',
  /**
   * Grants permission to update the metadata of a library item in the Q Business ap
   * plication environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_UpdateLibraryItemMetadata.html
   */
  UpdateLibraryItemMetadata = 'qapps:UpdateLibraryItemMetadata',
  /**
   * Grants permission to update Q App in the Q Business application environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_UpdateQApp.html
   */
  UpdateQApp = 'qapps:UpdateQApp',
  /**
   * Grants permission to update Q App sharing permissions in the Q Business applica
   * tion environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_UpdateQAppPermissions.html
   */
  UpdateQAppPermissions = 'qapps:UpdateQAppPermissions',
  /**
   * Grants permission to update Q App session in the Q Business application environ
   * ment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/api-reference/API_qapps_UpdateQAppSession.html
   */
  UpdateQAppSession = 'qapps:UpdateQAppSession',
  /**
   * Grants permission to update Q App session metadata in the Q Business applicatio
   * n environment
   *
   * See https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/purpose-built-qapps.html
   */
  UpdateQAppSessionMetadata = 'qapps:UpdateQAppSessionMetadata',
}
