// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Migration Hub Refactor Spaces (REFACTOR-SPACES)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsmigrationhubrefactorspaces.html
 *
 * 2025-02-24T21:48:57.841Z
 */
export enum AwsRefactorSpacesActions {
  /**
   * Grants permission to create an application within an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_CreateApplication.html
   */
  CreateApplication = 'refactor-spaces:CreateApplication',
  /**
   * Grants permission to create an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_CreateEnvironment.html
   */
  CreateEnvironment = 'refactor-spaces:CreateEnvironment',
  /**
   * Grants permission to create a route within an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_CreateRoute.html
   */
  CreateRoute = 'refactor-spaces:CreateRoute',
  /**
   * Grants permission to create a service within an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_CreateService.html
   */
  CreateService = 'refactor-spaces:CreateService',
  /**
   * Grants permission to delete an application from an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_DeleteApplication.html
   */
  DeleteApplication = 'refactor-spaces:DeleteApplication',
  /**
   * Grants permission to delete an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_DeleteEnvironment.html
   */
  DeleteEnvironment = 'refactor-spaces:DeleteEnvironment',
  /**
   * Grants permission to delete a resource policy
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_DeleteResourcePolicy.html
   */
  DeleteResourcePolicy = 'refactor-spaces:DeleteResourcePolicy',
  /**
   * Grants permission to delete a route from an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_DeleteRoute.html
   */
  DeleteRoute = 'refactor-spaces:DeleteRoute',
  /**
   * Grants permission to delete a service from an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_DeleteService.html
   */
  DeleteService = 'refactor-spaces:DeleteService',
  /**
   * Grants permission to get more information about an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_GetApplication.html
   */
  GetApplication = 'refactor-spaces:GetApplication',
  /**
   * Grants permission to get more information for an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_GetEnvironment.html
   */
  GetEnvironment = 'refactor-spaces:GetEnvironment',
  /**
   * Grants permission to get the details about a resource policy
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_GetResourcePolicy.html
   */
  GetResourcePolicy = 'refactor-spaces:GetResourcePolicy',
  /**
   * Grants permission to get more information about a route
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_GetRoute.html
   */
  GetRoute = 'refactor-spaces:GetRoute',
  /**
   * Grants permission to get more information about a service
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_GetService.html
   */
  GetService = 'refactor-spaces:GetService',
  /**
   * Grants permission to list all the applications in an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListApplications.html
   */
  ListApplications = 'refactor-spaces:ListApplications',
  /**
   * Grants permission to list all the VPCs for the environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListEnvironmentVpcs.html
   */
  ListEnvironmentVpcs = 'refactor-spaces:ListEnvironmentVpcs',
  /**
   * Grants permission to list all environments
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListEnvironments.html
   */
  ListEnvironments = 'refactor-spaces:ListEnvironments',
  /**
   * Grants permission to list all the routes in an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListRoutes.html
   */
  ListRoutes = 'refactor-spaces:ListRoutes',
  /**
   * Grants permission to list all the services in an environment
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListServices.html
   */
  ListServices = 'refactor-spaces:ListServices',
  /**
   * Grants permission to list all the tags for a given resource
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'refactor-spaces:ListTagsForResource',
  /**
   * Grants permission to add a resource policy
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_PutResourcePolicy.html
   */
  PutResourcePolicy = 'refactor-spaces:PutResourcePolicy',
  /**
   * Grants permission to tag a resource
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_TagResource.html
   */
  TagResource = 'refactor-spaces:TagResource',
  /**
   * Grants permission to remove a tag from a resource
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'refactor-spaces:UntagResource',
  /**
   * Grants permission to update a route from an application
   *
   * See https://docs.aws.amazon.com/migrationhub-refactor-spaces/latest/APIReference/API_UpdateRoute.html
   */
  UpdateRoute = 'refactor-spaces:UpdateRoute',
}
