// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Tag Editor (RESOURCE-EXPLORER)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_tageditor.html
 *
 * 2024-02-12T09:59:28.308Z
 */
export enum AwsResourceExplorerActions {
  /**
   * Grants permission to retrieve the resource types currently supported by Tag Edi
   * tor
   *
   * See https://docs.aws.amazon.com/ARG/latest/userguide/gettingstarted-prereqs.html#rg-permissions-te
   */
  ListResourceTypes = 'resource-explorer:ListResourceTypes',
  /**
   * Grants permission to retrieve the identifiers of the resources in the AWS accou
   * nt
   *
   * See https://docs.aws.amazon.com/ARG/latest/userguide/gettingstarted-prereqs.html#rg-permissions-te
   */
  ListResources = 'resource-explorer:ListResources',
  /**
   * Grants permission to retrieve the tags attached to the specified resource ident
   * ifiers
   *
   * See https://docs.aws.amazon.com/ARG/latest/userguide/gettingstarted-prereqs.html#rg-permissions-te
   */
  ListTags = 'resource-explorer:ListTags',
}
