// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Route 53 Resolver (ROUTE53RESOLVER)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonroute53resolver.html
 *
 * 2025-02-24T21:49:31.875Z
 */
export enum AwsRoute53resolverActions {
  /**
   * Grants permission to associate an Amazon VPC with a specified firewall rule gro
   * up
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_AssociateFirewallRuleGroup.html
   */
  AssociateFirewallRuleGroup = 'route53resolver:AssociateFirewallRuleGroup',
  /**
   * Grants permission to associate a specified IP address with a Resolver endpoint.
   * This is an IP address that DNS queries pass through on the way to your network
   * (outbound) or your VPCs (inbound)
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_AssociateResolverEndpointIpAddress.html
   */
  AssociateResolverEndpointIpAddress = 'route53resolver:AssociateResolverEndpointIpAddress',
  /**
   * Grants permission to associate an Amazon VPC with a specified query logging con
   * figuration
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_AssociateResolverQueryLogConfig.html
   */
  AssociateResolverQueryLogConfig = 'route53resolver:AssociateResolverQueryLogConfig',
  /**
   * Grants permission to associate a specified Resolver rule with a specified VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_AssociateResolverRule.html
   */
  AssociateResolverRule = 'route53resolver:AssociateResolverRule',
  /**
   * Grants permission to create a Firewall domain list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateFirewallDomainList.html
   */
  CreateFirewallDomainList = 'route53resolver:CreateFirewallDomainList',
  /**
   * Grants permission to create a Firewall rule within a Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateFirewallRule.html
   */
  CreateFirewallRule = 'route53resolver:CreateFirewallRule',
  /**
   * Grants permission to create a Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateFirewallRuleGroup.html
   */
  CreateFirewallRuleGroup = 'route53resolver:CreateFirewallRuleGroup',
  /**
   * Grants permission to create a Route 53 Resolver on Outposts
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateOutpostResolver.html
   */
  CreateOutpostResolver = 'route53resolver:CreateOutpostResolver',
  /**
   * Grants permission to create a Resolver endpoint. There are two types of Resolve
   * r endpoints, inbound and outbound
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html
   */
  CreateResolverEndpoint = 'route53resolver:CreateResolverEndpoint',
  /**
   * Grants permission to create a Resolver query logging configuration, which defin
   * es where you want Resolver to save DNS query logs that originate in your VPCs
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverQueryLogConfig.html
   */
  CreateResolverQueryLogConfig = 'route53resolver:CreateResolverQueryLogConfig',
  /**
   * Grants permission to define how to route queries originating from your VPC out
   * of the VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverRule.html
   */
  CreateResolverRule = 'route53resolver:CreateResolverRule',
  /**
   * Grants permission to delete a Firewall domain list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteFirewallDomainList.html
   */
  DeleteFirewallDomainList = 'route53resolver:DeleteFirewallDomainList',
  /**
   * Grants permission to delete a Firewall rule within a Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteFirewallRule.html
   */
  DeleteFirewallRule = 'route53resolver:DeleteFirewallRule',
  /**
   * Grants permission to delete a Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteFirewallRuleGroup.html
   */
  DeleteFirewallRuleGroup = 'route53resolver:DeleteFirewallRuleGroup',
  /**
   * Grants permission to delete a Route 53 Resolver on Outposts
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteOutpostResolver.html
   */
  DeleteOutpostResolver = 'route53resolver:DeleteOutpostResolver',
  /**
   * Grants permission to delete a Resolver endpoint. The effect of deleting a Resol
   * ver endpoint depends on whether it's an inbound or an outbound endpoint
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverEndpoint.html
   */
  DeleteResolverEndpoint = 'route53resolver:DeleteResolverEndpoint',
  /**
   * Grants permission to delete a Resolver query logging configuration
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverQueryLogConfig.html
   */
  DeleteResolverQueryLogConfig = 'route53resolver:DeleteResolverQueryLogConfig',
  /**
   * Grants permission to delete a Resolver rule
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverRule.html
   */
  DeleteResolverRule = 'route53resolver:DeleteResolverRule',
  /**
   * Grants permission to remove the association between a specified Firewall rule g
   * roup and a specified VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DisassociateFirewallRuleGroup.html
   */
  DisassociateFirewallRuleGroup = 'route53resolver:DisassociateFirewallRuleGroup',
  /**
   * Grants permission to remove a specified IP address from a Resolver endpoint. Th
   * is is an IP address that DNS queries pass through on the way to your network (o
   * utbound) or your VPCs (inbound)
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DisassociateResolverEndpointIpAddress.html
   */
  DisassociateResolverEndpointIpAddress = 'route53resolver:DisassociateResolverEndpointIpAddress',
  /**
   * Grants permission to remove the association between a specified Resolver query
   * logging configuration and a specified VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DisassociateResolverQueryLogConfig.html
   */
  DisassociateResolverQueryLogConfig = 'route53resolver:DisassociateResolverQueryLogConfig',
  /**
   * Grants permission to remove the association between a specified Resolver rule a
   * nd a specified VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DisassociateResolverRule.html
   */
  DisassociateResolverRule = 'route53resolver:DisassociateResolverRule',
  /**
   * Grants permission to get information about a specified Firewall config
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetFirewallConfig.html
   */
  GetFirewallConfig = 'route53resolver:GetFirewallConfig',
  /**
   * Grants permission to get information about a specified Firewall domain list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetFirewallDomainList.html
   */
  GetFirewallDomainList = 'route53resolver:GetFirewallDomainList',
  /**
   * Grants permission to get information about a specified Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetFirewallRuleGroup.html
   */
  GetFirewallRuleGroup = 'route53resolver:GetFirewallRuleGroup',
  /**
   * Grants permission to get information about an association between a specified F
   * irewall rule group and a VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetFirewallRuleGroupAssociation.html
   */
  GetFirewallRuleGroupAssociation = 'route53resolver:GetFirewallRuleGroupAssociation',
  /**
   * Grants permission to get information about a specified Firewall rule group poli
   * cy, which specifies the Firewall rule group operations and resources that you w
   * ant to allow another AWS account to use
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetFirewallRuleGroupPolicy.html
   */
  GetFirewallRuleGroupPolicy = 'route53resolver:GetFirewallRuleGroupPolicy',
  /**
   * Grants permission to get information about a specified Route 53 Resolver on Out
   * posts
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetOutpostResolver.html
   */
  GetOutpostResolver = 'route53resolver:GetOutpostResolver',
  /**
   * Grants permission to get the Resolver Config status within the specified resour
   * ce
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverConfig.html
   */
  GetResolverConfig = 'route53resolver:GetResolverConfig',
  /**
   * Grants permission to get the DNSSEC validation support status for DNS queries w
   * ithin the specified resource
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverDnssecConfig.html
   */
  GetResolverDnssecConfig = 'route53resolver:GetResolverDnssecConfig',
  /**
   * Grants permission to get information about a specified Resolver endpoint, such
   * as whether it's an inbound or an outbound endpoint, and the IP addresses in you
   * r VPC that DNS queries are forwarded to on the way into or out of your VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverEndpoint.html
   */
  GetResolverEndpoint = 'route53resolver:GetResolverEndpoint',
  /**
   * Grants permission to get information about a specified Resolver query logging c
   * onfiguration, such as the number of VPCs that the configuration is logging quer
   * ies for and the location that logs are sent to
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverQueryLogConfig.html
   */
  GetResolverQueryLogConfig = 'route53resolver:GetResolverQueryLogConfig',
  /**
   * Grants permission to get information about a specified association between a Re
   * solver query logging configuration and an Amazon VPC. When you associate a VPC
   * with a query logging configuration, Resolver logs DNS queries that originate in
   * that VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverQueryLogConfigAssociation.html
   */
  GetResolverQueryLogConfigAssociation = 'route53resolver:GetResolverQueryLogConfigAssociation',
  /**
   * Grants permission to get information about a specified Resolver query logging p
   * olicy, which specifies the Resolver query logging operations and resources that
   * you want to allow another AWS account to use
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverQueryLogConfigPolicy.html
   */
  GetResolverQueryLogConfigPolicy = 'route53resolver:GetResolverQueryLogConfigPolicy',
  /**
   * Grants permission to get information about a specified Resolver rule, such as t
   * he domain name that the rule forwards DNS queries for and the IP address that q
   * ueries are forwarded to
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRule.html
   */
  GetResolverRule = 'route53resolver:GetResolverRule',
  /**
   * Grants permission to get information about an association between a specified R
   * esolver rule and a VPC
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRuleAssociation.html
   */
  GetResolverRuleAssociation = 'route53resolver:GetResolverRuleAssociation',
  /**
   * Grants permission to get information about a Resolver rule policy, which specif
   * ies the Resolver operations and resources that you want to allow another AWS ac
   * count to use
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRulePolicy.html
   */
  GetResolverRulePolicy = 'route53resolver:GetResolverRulePolicy',
  /**
   * Grants permission to add, remove or replace Firewall domains in a Firewall doma
   * in list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ImportFirewallDomains.html
   */
  ImportFirewallDomains = 'route53resolver:ImportFirewallDomains',
  /**
   * Grants permission to list all the Firewall config that current AWS account is a
   * ble to check
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallConfigs.html
   */
  ListFirewallConfigs = 'route53resolver:ListFirewallConfigs',
  /**
   * Grants permission to list all the Firewall domain list that current AWS account
   * is able to use
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallDomainLists.html
   */
  ListFirewallDomainLists = 'route53resolver:ListFirewallDomainLists',
  /**
   * Grants permission to list all the Firewall domain under a specified Firewall do
   * main list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallDomains.html
   */
  ListFirewallDomains = 'route53resolver:ListFirewallDomains',
  /**
   * Grants permission to list information about associations between Amazon VPCs an
   * d Firewall rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallRuleGroupAssociations.html
   */
  ListFirewallRuleGroupAssociations = 'route53resolver:ListFirewallRuleGroupAssociations',
  /**
   * Grants permission to list all the Firewall rule group that current AWS account
   * is able to use
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallRuleGroups.html
   */
  ListFirewallRuleGroups = 'route53resolver:ListFirewallRuleGroups',
  /**
   * Grants permission to list all the Firewall rule under a specified Firewall rule
   * group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListFirewallRules.html
   */
  ListFirewallRules = 'route53resolver:ListFirewallRules',
  /**
   * Grants permission to list all instances of Route 53 Resolver on Outposts that w
   * ere created using the current AWS account
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListOutpostResolvers.html
   */
  ListOutpostResolvers = 'route53resolver:ListOutpostResolvers',
  /**
   * Grants permission to list Resolver Config statuses
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverConfigs.html
   */
  ListResolverConfigs = 'route53resolver:ListResolverConfigs',
  /**
   * Grants permission to list the DNSSEC validation support status for DNS queries
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverDnssecConfigs.html
   */
  ListResolverDnssecConfigs = 'route53resolver:ListResolverDnssecConfigs',
  /**
   * Grants permission to list the IP addresses that DNS queries pass through on the
   * way to your network (outbound) or your VPCs (inbound) for a specified Resolver
   * endpoint
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverEndpointIpAddresses.html
   */
  ListResolverEndpointIpAddresses = 'route53resolver:ListResolverEndpointIpAddresses',
  /**
   * Grants permission to list all the Resolver endpoints that were created using th
   * e current AWS account
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverEndpoints.html
   */
  ListResolverEndpoints = 'route53resolver:ListResolverEndpoints',
  /**
   * Grants permission to list information about associations between Amazon VPCs an
   * d query logging configurations
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverQueryLogConfigAssociations.html
   */
  ListResolverQueryLogConfigAssociations = 'route53resolver:ListResolverQueryLogConfigAssociations',
  /**
   * Grants permission to list information about the specified query logging configu
   * rations, which define where you want Resolver to save DNS query logs and specif
   * y the VPCs that you want to log queries for
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverQueryLogConfigs.html
   */
  ListResolverQueryLogConfigs = 'route53resolver:ListResolverQueryLogConfigs',
  /**
   * Grants permission to list the associations that were created between Resolver r
   * ules and VPCs using the current AWS account
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverRuleAssociations.html
   */
  ListResolverRuleAssociations = 'route53resolver:ListResolverRuleAssociations',
  /**
   * Grants permission to list the Resolver rules that were created using the curren
   * t AWS account
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverRules.html
   */
  ListResolverRules = 'route53resolver:ListResolverRules',
  /**
   * Grants permission to list the tags that you associated with the specified resou
   * rce
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListTagsForResource.html
   */
  ListTagsForResource = 'route53resolver:ListTagsForResource',
  /**
   * Grants permission to specify an AWS account that you want to share a Firewall r
   * ule group with, the Firewall rule group that you want to share, and the operati
   * ons that you want the account to be able to perform on the configuration
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_PutFirewallRuleGroupPolicy.html
   */
  PutFirewallRuleGroupPolicy = 'route53resolver:PutFirewallRuleGroupPolicy',
  /**
   * Grants permission to specify an AWS account that you want to share a query logg
   * ing configuration with, the query logging configuration that you want to share,
   * and the operations that you want the account to be able to perform on the confi
   * guration
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_PutResolverQueryLogConfigPolicy.html
   */
  PutResolverQueryLogConfigPolicy = 'route53resolver:PutResolverQueryLogConfigPolicy',
  /**
   * Grants permission to specify an AWS account that you want to share rules with,
   * the Resolver rules that you want to share, and the operations that you want the
   * account to be able to perform on those rules
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_PutResolverRulePolicy.html
   */
  PutResolverRulePolicy = 'route53resolver:PutResolverRulePolicy',
  /**
   * Grants permission to add one or more tags to a specified resource
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_TagResource.html
   */
  TagResource = 'route53resolver:TagResource',
  /**
   * Grants permission to remove one or more tags from a specified resource
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UntagResource.html
   */
  UntagResource = 'route53resolver:UntagResource',
  /**
   * Grants permission to update selected settings for an Firewall config
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateFirewallConfig.html
   */
  UpdateFirewallConfig = 'route53resolver:UpdateFirewallConfig',
  /**
   * Grants permission to add, remove or replace Firewall domains in a Firewall doma
   * in list
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateFirewallDomains.html
   */
  UpdateFirewallDomains = 'route53resolver:UpdateFirewallDomains',
  /**
   * Grants permission to update selected settings for an Firewall rule in a Firewal
   * l rule group
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateFirewallRule.html
   */
  UpdateFirewallRule = 'route53resolver:UpdateFirewallRule',
  /**
   * Grants permission to update selected settings for an Firewall rule group associ
   * ation
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateFirewallRuleGroupAssociation.html
   */
  UpdateFirewallRuleGroupAssociation = 'route53resolver:UpdateFirewallRuleGroupAssociation',
  /**
   * Grants permission to update seletected settings for a specified Route 53 Resolv
   * er on Outposts
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateOutpostResolver.html
   */
  UpdateOutpostResolver = 'route53resolver:UpdateOutpostResolver',
  /**
   * Grants permission to update the Resolver Config status within the specified res
   * ource
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverConfig.html
   */
  UpdateResolverConfig = 'route53resolver:UpdateResolverConfig',
  /**
   * Grants permission to update the DNSSEC validation support status for DNS querie
   * s within the specified resource
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverDnssecConfig.html
   */
  UpdateResolverDnssecConfig = 'route53resolver:UpdateResolverDnssecConfig',
  /**
   * Grants permission to update selected settings for an inbound or an outbound Res
   * olver endpoint
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverEndpoint.html
   */
  UpdateResolverEndpoint = 'route53resolver:UpdateResolverEndpoint',
  /**
   * Grants permission to update settings for a specified Resolver rule
   *
   * See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverRule.html
   */
  UpdateResolverRule = 'route53resolver:UpdateResolverRule',
}
