// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Supply Chain (SCN)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
 *
 * 2025-02-24T21:49:51.828Z
 */
export enum AwsScnActions {
  /**
   * Grants permission to add AWS Supply Chain administrator permission to federated
   * user
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  AssignAdminPermissionsToUser = 'scn:AssignAdminPermissionsToUser',
  /**
   * Grants permission to create a BillOfMaterialsImportJob which will import a CSV
   * file of BillOfMaterials records
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  CreateBillOfMaterialsImportJob = 'scn:CreateBillOfMaterialsImportJob',
  /**
   * Grants permission to create DataIntegrationFlow that can transform from multipl
   * e sources to one target
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  CreateDataIntegrationFlow = 'scn:CreateDataIntegrationFlow',
  /**
   * Grants permission to create the data lake dataset
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  CreateDataLakeDataset = 'scn:CreateDataLakeDataset',
  /**
   * Grants permission to create a new AWS Supply Chain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  CreateInstance = 'scn:CreateInstance',
  /**
   * Grants permission to create IAM Identity Center application for a AWS Supply Ch
   * ain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  CreateSSOApplication = 'scn:CreateSSOApplication',
  /**
   * Grants permission to delete the DataIntegrationFlow
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  DeleteDataIntegrationFlow = 'scn:DeleteDataIntegrationFlow',
  /**
   * Grants permission to delete the data lake dataset
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  DeleteDataLakeDataset = 'scn:DeleteDataLakeDataset',
  /**
   * Grants permission to delete an AWS Supply Chain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  DeleteInstance = 'scn:DeleteInstance',
  /**
   * Grants permission to delete IAM Identity Center application of the AWS Supply C
   * hain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  DeleteSSOApplication = 'scn:DeleteSSOApplication',
  /**
   * Grants permission to view details of an AWS Supply Chain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  DescribeInstance = 'scn:DescribeInstance',
  /**
   * Grants permission to view status and details of a BillOfMaterialsImportJob
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  GetBillOfMaterialsImportJob = 'scn:GetBillOfMaterialsImportJob',
  /**
   * Grants permission to get the DataIntegrationFlow details
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  GetDataIntegrationFlow = 'scn:GetDataIntegrationFlow',
  /**
   * Grants permission to get the dataset details
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  GetDataLakeDataset = 'scn:GetDataLakeDataset',
  /**
   * Grants permission to view details of an AWS Supply Chain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  GetInstance = 'scn:GetInstance',
  /**
   * Grants permission to list AWS Supply Chain administrators of an instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  ListAdminUsers = 'scn:ListAdminUsers',
  /**
   * Grants permission to list all the DataIntegrationFlows in a paginated way
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  ListDataIntegrationFlows = 'scn:ListDataIntegrationFlows',
  /**
   * Grants permission to list the data lake datasets under specific instance and na
   * mespace
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  ListDataLakeDatasets = 'scn:ListDataLakeDatasets',
  /**
   * Grants permission to view the AWS Supply Chain instances associated with an AWS
   * account
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  ListInstances = 'scn:ListInstances',
  /**
   * Grants permission to list tags for an AWS Supply Chain resource
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  ListTagsForResource = 'scn:ListTagsForResource',
  /**
   * Grants permission to remove AWS Supply Chain administrator permission from fede
   * rated user
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  RemoveAdminPermissionsForUser = 'scn:RemoveAdminPermissionsForUser',
  /**
   * Grants permission to create a DataIntegrationEvent which will ingest data in re
   * al-time
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  SendDataIntegrationEvent = 'scn:SendDataIntegrationEvent',
  /**
   * Grants permission to tag an AWS Supply Chain resource
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  TagResource = 'scn:TagResource',
  /**
   * Grants permission to remove tag from an AWS Supply Chain resource
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  UntagResource = 'scn:UntagResource',
  /**
   * Grants permission to update the DataIntegrationFlow
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  UpdateDataIntegrationFlow = 'scn:UpdateDataIntegrationFlow',
  /**
   * Grants permission to update the data lake dataset
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  UpdateDataLakeDataset = 'scn:UpdateDataLakeDataset',
  /**
   * Grants permission to update an AWS Supply Chain instance
   *
   * See https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupplychain.html
   */
  UpdateInstance = 'scn:UpdateInstance',
}
