// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Secrets Manager (SECRETSMANAGER)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssecretsmanager.html
 *
 * 2025-02-24T21:49:38.867Z
 */
export enum AwsSecretsmanagerActions {
  /**
   * Grants permission to retrieve and decrypt a list of secrets
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_BatchGetSecretValue.html
   */
  BatchGetSecretValue = 'secretsmanager:BatchGetSecretValue',
  /**
   * Grants permission to cancel an in-progress secret rotation
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CancelRotateSecret.html
   */
  CancelRotateSecret = 'secretsmanager:CancelRotateSecret',
  /**
   * Grants permission to create a secret that stores encrypted data that can be que
   * ried and rotated
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html
   */
  CreateSecret = 'secretsmanager:CreateSecret',
  /**
   * Grants permission to delete the resource policy attached to a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteResourcePolicy.html
   */
  DeleteResourcePolicy = 'secretsmanager:DeleteResourcePolicy',
  /**
   * Grants permission to delete a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html
   */
  DeleteSecret = 'secretsmanager:DeleteSecret',
  /**
   * Grants permission to retrieve the metadata about a secret, but not the encrypte
   * d data
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html
   */
  DescribeSecret = 'secretsmanager:DescribeSecret',
  /**
   * Grants permission to generate a random string for use in password creation
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetRandomPassword.html
   */
  GetRandomPassword = 'secretsmanager:GetRandomPassword',
  /**
   * Grants permission to get the resource policy attached to a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetResourcePolicy.html
   */
  GetResourcePolicy = 'secretsmanager:GetResourcePolicy',
  /**
   * Grants permission to retrieve and decrypt the encrypted data
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
   */
  GetSecretValue = 'secretsmanager:GetSecretValue',
  /**
   * Grants permission to list the available versions of a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ListSecretVersionIds.html
   */
  ListSecretVersionIds = 'secretsmanager:ListSecretVersionIds',
  /**
   * Grants permission to list the available secrets
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ListSecrets.html
   */
  ListSecrets = 'secretsmanager:ListSecrets',
  /**
   * Grants permission to attach a resource policy to a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_PutResourcePolicy.html
   */
  PutResourcePolicy = 'secretsmanager:PutResourcePolicy',
  /**
   * Grants permission to create a new version of the secret with new encrypted data
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_PutSecretValue.html
   */
  PutSecretValue = 'secretsmanager:PutSecretValue',
  /**
   * Grants permission to remove regions from replication
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RemoveRegionsFromReplication.html
   */
  RemoveRegionsFromReplication = 'secretsmanager:RemoveRegionsFromReplication',
  /**
   * Grants permission to convert an existing secret to a multi-Region secret and be
   * gin replicating the secret to a list of new regions
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ReplicateSecretToRegions.html
   */
  ReplicateSecretToRegions = 'secretsmanager:ReplicateSecretToRegions',
  /**
   * Grants permission to cancel deletion of a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RestoreSecret.html
   */
  RestoreSecret = 'secretsmanager:RestoreSecret',
  /**
   * Grants permission to start rotation of a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RotateSecret.html
   */
  RotateSecret = 'secretsmanager:RotateSecret',
  /**
   * Grants permission to remove the secret from replication and promote the secret
   * to a regional secret in the replica Region
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_StopReplicationToReplica.html
   */
  StopReplicationToReplica = 'secretsmanager:StopReplicationToReplica',
  /**
   * Grants permission to add tags to a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_TagResource.html
   */
  TagResource = 'secretsmanager:TagResource',
  /**
   * Grants permission to remove tags from a secret
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_UntagResource.html
   */
  UntagResource = 'secretsmanager:UntagResource',
  /**
   * Grants permission to update a secret with new metadata or with a new version of
   * the encrypted data
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_UpdateSecret.html
   */
  UpdateSecret = 'secretsmanager:UpdateSecret',
  /**
   * Grants permission to move a stage from one secret to another
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_UpdateSecretVersionStage.html
   */
  UpdateSecretVersionStage = 'secretsmanager:UpdateSecretVersionStage',
  /**
   * Grants permission to validate a resource policy before attaching policy
   *
   * See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ValidateResourcePolicy.html
   */
  ValidateResourcePolicy = 'secretsmanager:ValidateResourcePolicy',
}
