// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Microservice Extractor for .NET (SERVICEEXTRACT)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsmicroserviceextractorfor.net.html
 *
 * 2024-02-12T09:58:23.026Z
 */
export enum AwsServiceextractActions {
  /**
   * Grants permission to get required configuration for the AWS Microservice Extrac
   * tor for .NET desktop client
   *
   * See https://docs.aws.amazon.com/microservice-extractor/latest/userguide/what-is-microservice-extractor.html
   */
  GetConfig = 'serviceextract:GetConfig',
}
