// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Cloud Map (SERVICEDISCOVERY)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awscloudmap.html
 *
 * 2024-02-12T09:56:20.572Z
 */
export enum AwsServicediscoveryActions {
  /**
   * Grants permission to create an HTTP namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_CreateHttpNamespace.html
   */
  CreateHttpNamespace = 'servicediscovery:CreateHttpNamespace',
  /**
   * Grants permission to create a private namespace based on DNS, which will be vis
   * ible only inside a specified Amazon VPC
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_CreatePrivateDnsNamespace.html
   */
  CreatePrivateDnsNamespace = 'servicediscovery:CreatePrivateDnsNamespace',
  /**
   * Grants permission to create a public namespace based on DNS, which will be visi
   * ble on the internet
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_CreatePublicDnsNamespace.html
   */
  CreatePublicDnsNamespace = 'servicediscovery:CreatePublicDnsNamespace',
  /**
   * Grants permission to create a service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_CreateService.html
   */
  CreateService = 'servicediscovery:CreateService',
  /**
   * Grants permission to delete a specified namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_DeleteNamespace.html
   */
  DeleteNamespace = 'servicediscovery:DeleteNamespace',
  /**
   * Grants permission to delete a specified service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_DeleteService.html
   */
  DeleteService = 'servicediscovery:DeleteService',
  /**
   * Grants permission to delete the records and the health check, if any, that Amaz
   * on Route 53 created for the specified instance
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_DeregisterInstance.html
   */
  DeregisterInstance = 'servicediscovery:DeregisterInstance',
  /**
   * Grants permission to discover registered instances for a specified namespace an
   * d service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_DiscoverInstances.html
   */
  DiscoverInstances = 'servicediscovery:DiscoverInstances',
  /**
   * Grants permission to discover the revision of the instances for a specified nam
   * espace and service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_DiscoverInstancesRevision.html
   */
  DiscoverInstancesRevision = 'servicediscovery:DiscoverInstancesRevision',
  /**
   * Grants permission to get information about a specified instance
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_GetInstance.html
   */
  GetInstance = 'servicediscovery:GetInstance',
  /**
   * Grants permission to get the current health status (Healthy, Unhealthy, or Unkn
   * own) of one or more instances
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_GetInstancesHealthStatus.html
   */
  GetInstancesHealthStatus = 'servicediscovery:GetInstancesHealthStatus',
  /**
   * Grants permission to get information about a namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_GetNamespace.html
   */
  GetNamespace = 'servicediscovery:GetNamespace',
  /**
   * Grants permission to get information about a specific operation
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_GetOperation.html
   */
  GetOperation = 'servicediscovery:GetOperation',
  /**
   * Grants permission to get the settings for a specified service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_GetService.html
   */
  GetService = 'servicediscovery:GetService',
  /**
   * Grants permission to get summary information about the instances that were regi
   * stered with a specified service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_ListInstances.html
   */
  ListInstances = 'servicediscovery:ListInstances',
  /**
   * Grants permission to get information about the namespaces
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_ListNamespaces.html
   */
  ListNamespaces = 'servicediscovery:ListNamespaces',
  /**
   * Grants permission to list operations that match the criteria that you specify
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_ListOperations.html
   */
  ListOperations = 'servicediscovery:ListOperations',
  /**
   * Grants permission to get settings for all the services that match specified fil
   * ters
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_ListServices.html
   */
  ListServices = 'servicediscovery:ListServices',
  /**
   * Grants permission to lists tags for the specified resource
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_ListTagsForResource.html
   */
  ListTagsForResource = 'servicediscovery:ListTagsForResource',
  /**
   * Grants permission to register an instance based on the settings in a specified
   * service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_RegisterInstance.html
   */
  RegisterInstance = 'servicediscovery:RegisterInstance',
  /**
   * Grants permission to add one or more tags to the specified resource
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_TagResource.html
   */
  TagResource = 'servicediscovery:TagResource',
  /**
   * Grants permission to remove one or more tags from the specified resource
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UntagResource.html
   */
  UntagResource = 'servicediscovery:UntagResource',
  /**
   * Grants permission to update the settings for a HTTP namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdateHttpNamespace.html
   */
  UpdateHttpNamespace = 'servicediscovery:UpdateHttpNamespace',
  /**
   * Grants permission to update the current health status for an instance that has
   * a custom health check
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdateInstanceCustomHealthStatus.html
   */
  UpdateInstanceCustomHealthStatus = 'servicediscovery:UpdateInstanceCustomHealthStatus',
  /**
   * Grants permission to update the settings for a private DNS namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdatePrivateDnsNamespace.html
   */
  UpdatePrivateDnsNamespace = 'servicediscovery:UpdatePrivateDnsNamespace',
  /**
   * Grants permission to update the settings for a public DNS namespace
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdatePublicDnsNamespace.html
   */
  UpdatePublicDnsNamespace = 'servicediscovery:UpdatePublicDnsNamespace',
  /**
   * Grants permission to update the settings in a specified service
   *
   * See https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdateService.html
   */
  UpdateService = 'servicediscovery:UpdateService',
}
