// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Signer (SIGNER)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssigner.html
 *
 * 2025-02-24T21:49:44.830Z
 */
export enum AwsSignerActions {
  /**
   * Grants permission to add cross-account permissions to a Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_AddProfilePermission.html
   */
  AddProfilePermission = 'signer:AddProfilePermission',
  /**
   * Grants permission to change the state of a Signing Profile to CANCELED
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_CancelSigningProfile.html
   */
  CancelSigningProfile = 'signer:CancelSigningProfile',
  /**
   * Grants permission to return information about a specific Signing Job
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_DescribeSigningJob.html
   */
  DescribeSigningJob = 'signer:DescribeSigningJob',
  /**
   * Grants permission to query revocation info of signing resources
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_GetRevocationStatus.html
   */
  GetRevocationStatus = 'signer:GetRevocationStatus',
  /**
   * Grants permission to return information about a specific Signing Platform
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_GetSigningPlatform.html
   */
  GetSigningPlatform = 'signer:GetSigningPlatform',
  /**
   * Grants permission to return information about a specific Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_GetSigningProfile.html
   */
  GetSigningProfile = 'signer:GetSigningProfile',
  /**
   * Grants permission to list the cross-account permissions associated with a Signi
   * ng Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_ListProfilePermissions.html
   */
  ListProfilePermissions = 'signer:ListProfilePermissions',
  /**
   * Grants permission to list all Signing Jobs in your account
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_ListSigningJobs.html
   */
  ListSigningJobs = 'signer:ListSigningJobs',
  /**
   * Grants permission to list all available Signing Platforms
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_ListSigningPlatforms.html
   */
  ListSigningPlatforms = 'signer:ListSigningPlatforms',
  /**
   * Grants permission to list all Signing Profiles in your account
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_ListSigningProfiles.html
   */
  ListSigningProfiles = 'signer:ListSigningProfiles',
  /**
   * Grants permission to list the tags associated with a Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_ListTagsForResource.html
   */
  ListTagsForResource = 'signer:ListTagsForResource',
  /**
   * Grants permission to create a new Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_PutSigningProfile.html
   */
  PutSigningProfile = 'signer:PutSigningProfile',
  /**
   * Grants permission to remove cross-account permissions from a Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_RemoveProfilePermission.html
   */
  RemoveProfilePermission = 'signer:RemoveProfilePermission',
  /**
   * Grants permission to change the state of a Signing Job to REVOKED
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_RevokeSignature.html
   */
  RevokeSignature = 'signer:RevokeSignature',
  /**
   * Grants permission to change the state of a Signing Profile to REVOKED
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_RevokeSigningProfile.html
   */
  RevokeSigningProfile = 'signer:RevokeSigningProfile',
  /**
   * Grants permission to initiate a Signing Job on the provided payload
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_SignPayload.html
   */
  SignPayload = 'signer:SignPayload',
  /**
   * Grants permission to initiate a Signing Job on the provided code
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_StartSigningJob.html
   */
  StartSigningJob = 'signer:StartSigningJob',
  /**
   * Grants permission to add one or more tags to a Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_TagResource.html
   */
  TagResource = 'signer:TagResource',
  /**
   * Grants permission to remove one or more tags from a Signing Profile
   *
   * See https://docs.aws.amazon.com/signer/latest/api/API_UntagResource.html
   */
  UntagResource = 'signer:UntagResource',
}
