// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon SQS (SQS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsqs.html
 *
 * 2025-02-24T21:49:50.264Z
 */
export enum AwsSqsActions {
  /**
   * Grants permission to a queue for a specific principal
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html
   */
  AddPermission = 'sqs:AddPermission',
  /**
   * Grants permission to cancel an in progress message move task
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CancelMessageMoveTask.html
   */
  CancelMessageMoveTask = 'sqs:CancelMessageMoveTask',
  /**
   * Grants permission to change the visibility timeout of a specified message in a
   * queue to a new value
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html
   */
  ChangeMessageVisibility = 'sqs:ChangeMessageVisibility',
  /**
   * Grants permission to create a new queue, or returns the URL of an existing one
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html
   */
  CreateQueue = 'sqs:CreateQueue',
  /**
   * Grants permission to delete the specified message from the specified queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html
   */
  DeleteMessage = 'sqs:DeleteMessage',
  /**
   * Grants permission to delete the queue specified by the queue URL, regardless of
   * whether the queue is empty
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteQueue.html
   */
  DeleteQueue = 'sqs:DeleteQueue',
  /**
   * Grants permission to get attributes for the specified queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html
   */
  GetQueueAttributes = 'sqs:GetQueueAttributes',
  /**
   * Grants permission to return the URL of an existing queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html
   */
  GetQueueUrl = 'sqs:GetQueueUrl',
  /**
   * Grants permission to return a list of your queues that have the RedrivePolicy q
   * ueue attribute configured with a dead letter queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListDeadLetterSourceQueues.html
   */
  ListDeadLetterSourceQueues = 'sqs:ListDeadLetterSourceQueues',
  /**
   * Grants permission to list message move tasks
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListMessageMoveTasks.html
   */
  ListMessageMoveTasks = 'sqs:ListMessageMoveTasks',
  /**
   * Grants permission to list tags added to an SQS queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListQueueTags.html
   */
  ListQueueTags = 'sqs:ListQueueTags',
  /**
   * Grants permission to return a list of your queues
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListQueues.html
   */
  ListQueues = 'sqs:ListQueues',
  /**
   * Grants permission to delete the messages in a queue specified by the queue URL
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_PurgeQueue.html
   */
  PurgeQueue = 'sqs:PurgeQueue',
  /**
   * Grants permission to retrieve one or more messages, with a maximum limit of 10
   * messages, from the specified queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
   */
  ReceiveMessage = 'sqs:ReceiveMessage',
  /**
   * Grants permission to revoke any permissions in the queue policy that matches th
   * e specified Label parameter
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_RemovePermission.html
   */
  RemovePermission = 'sqs:RemovePermission',
  /**
   * Grants permission to deliver a message to the specified queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html
   */
  SendMessage = 'sqs:SendMessage',
  /**
   * Grants permission to set the value of one or more queue attributes
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
   */
  SetQueueAttributes = 'sqs:SetQueueAttributes',
  /**
   * Grants permission to start a message move task
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_StartMessageMoveTask.html
   */
  StartMessageMoveTask = 'sqs:StartMessageMoveTask',
  /**
   * Grants permission to add tags to the specified SQS queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_TagQueue.html
   */
  TagQueue = 'sqs:TagQueue',
  /**
   * Grants permission to remove tags from the specified SQS queue
   *
   * See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_UntagQueue.html
   */
  UntagQueue = 'sqs:UntagQueue',
}
