// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS IAM Identity Center OIDC service (SSO-OAUTH)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiamidentitycenteroidcservice.html
 *
 * 2025-02-24T21:48:14.515Z
 */
export enum AwsSsoOauthActions {
  /**
   * Grants permission to create OAuth/OIDC tokens to access IAM Identity Center int
   * egrated applications
   *
   * See https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/API_CreateTokenWithIAM.html
   */
  CreateTokenWithIAM = 'sso-oauth:CreateTokenWithIAM',
}
