// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for AWS Support (SUPPORT)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssupport.html
 *
 * 2025-02-24T21:49:52.292Z
 */
export enum AwsSupportActions {
  /**
   * Grants permission to add one or more attachments to an AWS Support case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_AddAttachmentsToSet.html
   */
  AddAttachmentsToSet = 'support:AddAttachmentsToSet',
  /**
   * Grants permission to add a customer communication to an AWS Support case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_AddCommunicationToCase.html
   */
  AddCommunicationToCase = 'support:AddCommunicationToCase',
  /**
   * Grants permission to creates a new AWS Support case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_CreateCase.html
   */
  CreateCase = 'support:CreateCase',
  /**
   * Grants permission to describe attachment detail
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeAttachment.html
   */
  DescribeAttachment = 'support:DescribeAttachment',
  /**
   * Grants permission to allow secondary services to read AWS Support case attribut
   * es.This is an internally managed function
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  DescribeCaseAttributes = 'support:DescribeCaseAttributes',
  /**
   * Grants permission to list AWS Support cases that matches the given inputs
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeCases.html
   */
  DescribeCases = 'support:DescribeCases',
  /**
   * Grants permission to get a single communication and attachments for a single AW
   * S Support case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  DescribeCommunication = 'support:DescribeCommunication',
  /**
   * Grants permission to list the communications and attachments for one or more AW
   * S Support cases
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeCommunications.html
   */
  DescribeCommunications = 'support:DescribeCommunications',
  /**
   * Grants permission to describes the available options for creating a support cas
   * e
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeCreateCaseOptions.html
   */
  DescribeCreateCaseOptions = 'support:DescribeCreateCaseOptions',
  /**
   * Grants permission to return issue types for AWS Support cases
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  DescribeIssueTypes = 'support:DescribeIssueTypes',
  /**
   * Grants permission to list AWS services and categories that applies to each serv
   * ice
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeServices.html
   */
  DescribeServices = 'support:DescribeServices',
  /**
   * Grants permission to list severity levels that can be assigned to an AWS Suppor
   * t case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeSeverityLevels.html
   */
  DescribeSeverityLevels = 'support:DescribeSeverityLevels',
  /**
   * Grants permission to return the support level for an AWS Account identifier
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  DescribeSupportLevel = 'support:DescribeSupportLevel',
  /**
   * Grants permission to describes the available support languages for a given cate
   * gory code, service code and issue type
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeSupportedLanguages.html
   */
  DescribeSupportedLanguages = 'support:DescribeSupportedLanguages',
  /**
   * Grants permission to get the status of a Trusted Advisor refresh check based on
   * a list of check identifiers
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorCheckRefreshStatuses.html
   */
  DescribeTrustedAdvisorCheckRefreshStatuses = 'support:DescribeTrustedAdvisorCheckRefreshStatuses',
  /**
   * Grants permission to get the results of the Trusted Advisor check that has the
   * specified check identifier
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorCheckResult.html
   */
  DescribeTrustedAdvisorCheckResult = 'support:DescribeTrustedAdvisorCheckResult',
  /**
   * Grants permission to get the summaries of the results of the Trusted Advisor ch
   * ecks that have the specified check identifiers
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorCheckSummaries.html
   */
  DescribeTrustedAdvisorCheckSummaries = 'support:DescribeTrustedAdvisorCheckSummaries',
  /**
   * Grants permission to get a list of all available Trusted Advisor checks, includ
   * ing name, identifier, category and description
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorChecks.html
   */
  DescribeTrustedAdvisorChecks = 'support:DescribeTrustedAdvisorChecks',
  /**
   * Grants permission to initiate a call on AWS Support Center. This is an internal
   * ly managed function
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  InitiateCallForCase = 'support:InitiateCallForCase',
  /**
   * Grants permission to initiate a chat on AWS Support Center.This is an internall
   * y managed function
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  InitiateChatForCase = 'support:InitiateChatForCase',
  /**
   * Grants permission to allow secondary services to attach attributes to AWS Suppo
   * rt cases. This is an internally managed function
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  PutCaseAttributes = 'support:PutCaseAttributes',
  /**
   * Grants permission to rate an AWS Support case communication
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  RateCaseCommunication = 'support:RateCaseCommunication',
  /**
   * Grants permission to requests a refresh of the Trusted Advisor check that has t
   * he specified check identifier
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_RefreshTrustedAdvisorCheck.html
   */
  RefreshTrustedAdvisorCheck = 'support:RefreshTrustedAdvisorCheck',
  /**
   * Grants permission to resolve an AWS Support case
   *
   * See https://docs.aws.amazon.com/awssupport/latest/APIReference/API_ResolveCase.html
   */
  ResolveCase = 'support:ResolveCase',
  /**
   * Grants permission to return a list of AWS Support cases that matches the given
   * inputs
   *
   * See https://docs.aws.amazon.com/awssupport/latest/user/accessing-support.html
   */
  SearchForCases = 'support:SearchForCases',
}
