// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Verified Permissions (VERIFIEDPERMISSIONS)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonverifiedpermissions.html
 *
 * 2024-02-12T09:59:35.992Z
 */
export enum AwsVerifiedpermissionsActions {
  /**
   * Grants permission to create a reference to an external identity provider (IdP)
   * that is compatible with OpenID Connect (OIDC) authentication protocol, such as
   * Amazon Cognito
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreateIdentitySource.html
   */
  CreateIdentitySource = 'verifiedpermissions:CreateIdentitySource',
  /**
   * Grants permission to create a Cedar policy and save it in the specified policy
   * store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicy.html
   */
  CreatePolicy = 'verifiedpermissions:CreatePolicy',
  /**
   * Grants permission to create a Cedar policy and save it in the specified policy
   * store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicyStore.html
   */
  CreatePolicyStore = 'verifiedpermissions:CreatePolicyStore',
  /**
   * Grants permission to create a policy template
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicyTemplate.html
   */
  CreatePolicyTemplate = 'verifiedpermissions:CreatePolicyTemplate',
  /**
   * Grants permission to delete an identity source that references an identity prov
   * ider (IdP) such as Amazon Cognito
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_DeleteIdentitySource.html
   */
  DeleteIdentitySource = 'verifiedpermissions:DeleteIdentitySource',
  /**
   * Grants permission to delete the specified policy from the policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_DeletePolicy.html
   */
  DeletePolicy = 'verifiedpermissions:DeletePolicy',
  /**
   * Grants permission to delete the specified policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_DeletePolicyStore.html
   */
  DeletePolicyStore = 'verifiedpermissions:DeletePolicyStore',
  /**
   * Grants permission to delete the specified policy template from the policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_DeletePolicyTemplate.html
   */
  DeletePolicyTemplate = 'verifiedpermissions:DeletePolicyTemplate',
  /**
   * Grants permission to retrieve the details about the specified identity source
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetIdentitySource.html
   */
  GetIdentitySource = 'verifiedpermissions:GetIdentitySource',
  /**
   * Grants permission to retrieve information about the specified policy
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetPolicy.html
   */
  GetPolicy = 'verifiedpermissions:GetPolicy',
  /**
   * Grants permission to retrieve details about a policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetPolicyStore.html
   */
  GetPolicyStore = 'verifiedpermissions:GetPolicyStore',
  /**
   * Grants permission to retrieve the details for the specified policy template in
   * the specified policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetPolicyTemplate.html
   */
  GetPolicyTemplate = 'verifiedpermissions:GetPolicyTemplate',
  /**
   * Grants permission to retrieve the details for the specified schema in the speci
   * fied policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetSchema.html
   */
  GetSchema = 'verifiedpermissions:GetSchema',
  /**
   * Grants permission to make an authorization decision about a service request des
   * cribed in the parameters
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_IsAuthorized.html
   */
  IsAuthorized = 'verifiedpermissions:IsAuthorized',
  /**
   * Grants permission to make an authorization decision about a service request des
   * cribed in the parameters. The principal in this request comes from an external
   * identity source
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_IsAuthorizedWithToken.html
   */
  IsAuthorizedWithToken = 'verifiedpermissions:IsAuthorizedWithToken',
  /**
   * Grants permission to return a paginated list of all of the identity sources def
   * ined in the specified policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_ListIdentitySources.html
   */
  ListIdentitySources = 'verifiedpermissions:ListIdentitySources',
  /**
   * Grants permission to return a paginated list of all policies stored in the spec
   * ified policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_ListPolicies.html
   */
  ListPolicies = 'verifiedpermissions:ListPolicies',
  /**
   * Grants permission to return a paginated list of all policy stores in the callin
   * g Amazon Web Services account
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_ListPolicyStores.html
   */
  ListPolicyStores = 'verifiedpermissions:ListPolicyStores',
  /**
   * Grants permission to return a paginated list of all policy templates in the spe
   * cified policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_ListPolicyTemplates.html
   */
  ListPolicyTemplates = 'verifiedpermissions:ListPolicyTemplates',
  /**
   * Grants permission to create or update the policy schema in the specified policy
   * store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_PutSchema.html
   */
  PutSchema = 'verifiedpermissions:PutSchema',
  /**
   * Grants permission to update the specified identity source to use a new identity
   * provider (IdP) source, or to change the mapping of identities from the IdP to a
   * different principal entity type
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_UpdateIdentitySource.html
   */
  UpdateIdentitySource = 'verifiedpermissions:UpdateIdentitySource',
  /**
   * Grants permission to modify the specified Cedar static policy in the specified
   * policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_UpdatePolicy.html
   */
  UpdatePolicy = 'verifiedpermissions:UpdatePolicy',
  /**
   * Grants permission to modify the validation setting for a policy store
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_UpdatePolicyStore.html
   */
  UpdatePolicyStore = 'verifiedpermissions:UpdatePolicyStore',
  /**
   * Grants permission to update the specified policy template
   *
   * See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_UpdatePolicyTemplate.html
   */
  UpdatePolicyTemplate = 'verifiedpermissions:UpdatePolicyTemplate',
}
