// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon Connect Voice ID (VOICEID)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonconnectvoiceid.html
 *
 * 2025-02-24T21:47:25.492Z
 */
export enum AwsVoiceidActions {
  /**
   * Grants permission to associate a fraudster with a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_AssociateFraudster.html
   */
  AssociateFraudster = 'voiceid:AssociateFraudster',
  /**
   * Grants permission to create a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_CreateDomain.html
   */
  CreateDomain = 'voiceid:CreateDomain',
  /**
   * Grants permission to create a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_CreateWatchlist.html
   */
  CreateWatchlist = 'voiceid:CreateWatchlist',
  /**
   * Grants permission to delete a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DeleteDomain.html
   */
  DeleteDomain = 'voiceid:DeleteDomain',
  /**
   * Grants permission to delete a fraudster
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DeleteFraudster.html
   */
  DeleteFraudster = 'voiceid:DeleteFraudster',
  /**
   * Grants permission to delete a speaker
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DeleteSpeaker.html
   */
  DeleteSpeaker = 'voiceid:DeleteSpeaker',
  /**
   * Grants permission to delete a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DeleteWatchlist.html
   */
  DeleteWatchlist = 'voiceid:DeleteWatchlist',
  /**
   * Grants permission to describe compliance consent
   *
   * See https://docs.aws.amazon.com/connect/latest/adminguide/enable-voiceid.html#enable-voiceid-step1
   */
  DescribeComplianceConsent = 'voiceid:DescribeComplianceConsent',
  /**
   * Grants permission to describe a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeDomain.html
   */
  DescribeDomain = 'voiceid:DescribeDomain',
  /**
   * Grants permission to describe a fraudster
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeFraudster.html
   */
  DescribeFraudster = 'voiceid:DescribeFraudster',
  /**
   * Grants permission to describe a fraudster registration job
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeFraudsterRegistrationJob.html
   */
  DescribeFraudsterRegistrationJob = 'voiceid:DescribeFraudsterRegistrationJob',
  /**
   * Grants permission to describe a speaker
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeSpeaker.html
   */
  DescribeSpeaker = 'voiceid:DescribeSpeaker',
  /**
   * Grants permission to describe a speaker enrollment job
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeSpeakerEnrollmentJob.html
   */
  DescribeSpeakerEnrollmentJob = 'voiceid:DescribeSpeakerEnrollmentJob',
  /**
   * Grants permission to describe a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DescribeWatchlist.html
   */
  DescribeWatchlist = 'voiceid:DescribeWatchlist',
  /**
   * Grants permission to disassociate a fraudster from a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_DisassociateFraudster.html
   */
  DisassociateFraudster = 'voiceid:DisassociateFraudster',
  /**
   * Grants permission to evaluate a session
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_EvaluateSession.html
   */
  EvaluateSession = 'voiceid:EvaluateSession',
  /**
   * Grants permission to list domains for an account
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListDomains.html
   */
  ListDomains = 'voiceid:ListDomains',
  /**
   * Grants permission to list fraudster registration jobs for a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListFraudsterRegistrationJobs.html
   */
  ListFraudsterRegistrationJobs = 'voiceid:ListFraudsterRegistrationJobs',
  /**
   * Grants permission to list fraudsters for a domain or watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListFraudsters.html
   */
  ListFraudsters = 'voiceid:ListFraudsters',
  /**
   * Grants permission to list speaker enrollment jobs for a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListSpeakerEnrollmentJobs.html
   */
  ListSpeakerEnrollmentJobs = 'voiceid:ListSpeakerEnrollmentJobs',
  /**
   * Grants permission to list speakers for a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListSpeakers.html
   */
  ListSpeakers = 'voiceid:ListSpeakers',
  /**
   * Grants permission to list tags for a Voice ID resource
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListTagsForResource.html
   */
  ListTagsForResource = 'voiceid:ListTagsForResource',
  /**
   * Grants permission to list watchlists for a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_ListWatchlists.html
   */
  ListWatchlists = 'voiceid:ListWatchlists',
  /**
   * Grants permission to opt out a speaker
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_OptOutSpeaker.html
   */
  OptOutSpeaker = 'voiceid:OptOutSpeaker',
  /**
   * Grants permission to register compliance consent
   *
   * See https://docs.aws.amazon.com/connect/latest/adminguide/enable-voiceid.html#enable-voiceid-step1
   */
  RegisterComplianceConsent = 'voiceid:RegisterComplianceConsent',
  /**
   * Grants permission to start a fraudster registration job
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_StartFraudsterRegistrationJob.html
   */
  StartFraudsterRegistrationJob = 'voiceid:StartFraudsterRegistrationJob',
  /**
   * Grants permission to start a speaker enrollment job
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_StartSpeakerEnrollmentJob.html
   */
  StartSpeakerEnrollmentJob = 'voiceid:StartSpeakerEnrollmentJob',
  /**
   * Grants permission to tag a Voice ID resource
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_TagResource.html
   */
  TagResource = 'voiceid:TagResource',
  /**
   * Grants permission to remove a tag from a Voice ID resource
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_UntagResource.html
   */
  UntagResource = 'voiceid:UntagResource',
  /**
   * Grants permission to update a domain
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_UpdateDomain.html
   */
  UpdateDomain = 'voiceid:UpdateDomain',
  /**
   * Grants permission to update a watchlist
   *
   * See https://docs.aws.amazon.com/voiceid/latest/APIReference/API_UpdateWatchlist.html
   */
  UpdateWatchlist = 'voiceid:UpdateWatchlist',
}
