// AUTOGENERATED FILE - DO NOT EDIT

/**
 * All IAM policy actions for Amazon WorkSpaces Application Manager (WAM)
 *
 * Extracted by `aws-iam-policy` from
 * https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonworkspacesapplicationmanager.html
 *
 * 2025-02-24T21:50:12.028Z
 */
export enum AwsWamActions {
  /**
   * Allows the Amazon WAM packaging instance to access your application package cat
   * alog.
   *
   * See https://docs.aws.amazon.com/wam/latest/adminguide/iam.html
   */
  AuthenticatePackager = 'wam:AuthenticatePackager',
}
